//! `cargo run --example fmuinfo -- <file.fmu>…` — what the importer reads out of
//! an FMU. Handy when an FMU will not load and the question is what the FMU says
//! about itself.

use openmodelica_fmi::{Fmu, InterfaceKind, Preference};

fn main() {
    let mut bad = false;
    for path in std::env::args().skip(1) {
        match dump(&path) {
            Ok(()) => {}
            Err(e) => {
                println!("{path}: {e}");
                bad = true;
            }
        }
    }
    if bad {
        std::process::exit(1);
    }
}

fn dump(path: &str) -> Result<(), Box<dyn std::error::Error>> {
    let fmu = Fmu::from_path(std::path::Path::new(path))?;
    let md = &fmu.model_description;
    println!("{path}");
    println!("  FMI {} — {}", md.fmi_version_string, md.model_name);
    println!("  token {}", md.instantiation_token);
    if let Some(tool) = &md.generation_tool {
        println!("  generated by {tool}");
    }
    for kind in md.interfaces() {
        let i = md.interface(kind).unwrap();
        print!("  {} ({})", kind.as_str(), i.model_identifier);
        if i.has_event_mode {
            print!(" event-mode");
        }
        if i.might_return_early_from_do_step {
            print!(" early-return");
        }
        if i.can_get_and_set_state {
            print!(" fmu-state");
        }
        println!();
        for b in fmu.binaries(kind) {
            println!("    {} {:?}{}", b.platform_dir, b.kind, if b.is_host { " (host)" } else { "" });
        }
        if let Some(b) = fmu.select_binary(kind, Preference::Native) {
            println!("    chosen: {}", b.path);
        }
    }
    println!(
        "  {} variables, {} states, {} event indicators",
        md.variables.len(),
        md.number_of_continuous_states(),
        md.number_of_event_indicators
    );
    if let Some(e) = md.default_experiment {
        println!(
            "  experiment {:?}..{:?} tol {:?} step {:?}",
            e.start_time, e.stop_time, e.tolerance, e.step_size
        );
    }
    for vr in md.continuous_states() {
        if let Some(v) = md.variable_by_vr(vr) {
            println!("    state {} (vr {vr})", v.name);
        }
    }
    for v in md.variables.iter().filter(|v| v.is_settable()) {
        println!(
            "    {:?} {} = {:?}{}",
            v.causality,
            v.name,
            v.start.as_ref().and_then(|s| s.first_f64()),
            v.unit.as_deref().map(|u| format!(" [{u}]")).unwrap_or_default()
        );
    }
    #[cfg(feature = "component")]
    if let Some(b) = fmu.select_binary(InterfaceKind::CoSimulation, Preference::Wasm)
        .or_else(|| fmu.select_binary(InterfaceKind::ModelExchange, Preference::Wasm))
    {
        if b.kind == openmodelica_fmi::BinaryKind::Wasm {
            let bytes = fmu.read(&b.path).unwrap();
            match openmodelica_fmi::lswasm::inspect(&bytes) {
                Ok(c) => {
                    println!("  component: {:?}, wasi {:?}", c.interfaces, c.wasi);
                    for m in &c.core_modules {
                        println!(
                            "    core module {} — {} imports, {} exports{}{}",
                            m.index,
                            m.imports.len(),
                            m.exports.len(),
                            if m.memory.is_some() { ", memory" } else { "" },
                            if m.is_wasi_adapter { ", wasi adapter" } else { "" }
                        );
                    }
                }
                Err(e) => println!("  component: {e}"),
            }
        }
    }
    Ok(())
}
