.PHONY: install build OMEdit

install: build
	cp ../bin/OMEdit ../../build/bin/
	mkdir -p ../../build/share/doc/omedit/
	cp -p ../docs/*.pdf ../../build/share/doc/omedit/
OMEdit: build
build:
	ln -sf ../OMNotebook/3Dpkg ../
	ln -sf ../OMNotebook/Pltpkg2 ../
	qmake && $(MAKE) -f Makefile
