#
# Makefile for Compiler/runtime/FMI
#

top_builddir= ../../..
builddir_lib=$(top_builddir)/build/lib

LIB = libfmiwrapper.a

CSRC	= FMI_rml.c FMIWrapper.c
OBJ = $(SRC:.c=.o)
FMI_OBJ = FMI_rml.o FMIWrapper.o

all: $(LIB) install
.PHONY: all install
$(LIB) : $(FMI_OBJ)
	rm -f $@
	$(AR) -s -r $@ $(FMI_OBJ)
install: $(LIB)
	cp $(LIB) $(builddir_lib)/omc/

FMI_rml.o : FMIImpl.c

clean:
	$(RM) -rf *.a *.o
