.\" --------------------------------------------------------------------
.\" Title 
.\" -------------------------------------------------------------------- 
.
.TH omlibrary 1 "The Open Source Modelica Consortium" "1.5.0" "The OpenModelica Project" -*- nroff -*-
.
.
.\" --------------------------------------------------------------------
.SH "NAME"
.\" -------------------------------------------------------------------- 
.
omlibrary \- Modelica library of the \%OpenModelica Project
.
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B omlibrary
is a adapted version of the Modelica library for the \%OpenModelica Project.
The \%OpenModelica Compiler/Interpreter \fBomc\fP need the library, if programmer
use Modelica classes in here or his models.
.
.
.
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.\" --------------------------------------------------------------------
.
.TP
.B OPENMODELICALIBRARY
Absolute path towards the OpenModelica library \fBModelica\fP.
.sp
Default directory: \fI/usr/share/omlibrary/modelicalib/\fP
.
.
.
.\" --------------------------------------------------------------------
.SH LINKS
.\" --------------------------------------------------------------------
.
.TP
.B Home of the official Modelica library
.sp
WWW address: \fIhttp://www.modelica.org\fP
.
.
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR omc (1).
.
.
.
.\" --------------------------------------------------------------------
.SH AUTHOR
.\" --------------------------------------------------------------------
.
The original author was William Spinelli. Changes and improvements were made
by Robert Wotzlaw <Robert.Wotzlaw at web.de>.
.P
The current author isn't a member of the Open Source Modelica Consortium (OSMC)
nor a collaborator at the Programming Environment Laboratory (PELAB),
Department of Computer and Information Science (IDA) of the Linkoeping
University (LiU). He supports the OpenModelica Project as volunteer.
