.\" --------------------------------------------------------------------
.\" Title 
.\" -------------------------------------------------------------------- 
.
.TH omlibrary 1 "The Open Source Modelica Consortium" "1.7.0" "The OpenModelica Project" -*- nroff -*-
.
.
.\" --------------------------------------------------------------------
.SH "NAME"
.\" -------------------------------------------------------------------- 
.
omlibrary \- Modelica library of the \%OpenModelica Project
.
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B omlibrary
is a adapted version of the Modelica Standard Library for the \%OpenModelica Project.
The \%OpenModelica Compiler/Interpreter \fBomc\fP needs the library if a
programmer uses Modelica classes in his or her models.
.
.
.\" --------------------------------------------------------------------
.SH LINKS
.\" --------------------------------------------------------------------
.
.TP
.B Home of the official Modelica library
.sp
WWW address: \fIhttp://www.modelica.org\fP
.
.
.\" --------------------------------------------------------------------
.SH AUTHOR
.\" --------------------------------------------------------------------
.
See OpenModelicaUsersGuide.pdf for a full list of contributors to the
\%OpenModelica project.
.
.\" --------------------------------------------------------------------
.SH BUGS
.\" --------------------------------------------------------------------
.
If you find a bug, please report it at the Modelica or OpenModelica bug
tracker:
.RS
.P
<\fBhttps://trac.modelica.org/Modelica\fR>
.P
<\fBhttp://openmodelica.org:8080/cb/project/1\fR>
.RE
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR omc (1)
