.\" --------------------------------------------------------------------
.\" Title 
.\" --------------------------------------------------------------------
.
.TH omc 1 "The Open Source Modelica Consortium" "1.5.0" "The OpenModelica Project" -*- nroff -*-
.
.
.\" --------------------------------------------------------------------
.SH "NAME"
.\" --------------------------------------------------------------------
.
OMPlotWindow \- OpenModelica external plot viewer
