
/*
 Adrian Pop, 2006-01-24
 These defines are used to map java names of RML external 
 relation implemented in C to normal RML names
 it should be included in all the files that call
 the external relations.
 */

#ifndef __EXTERNALRMLDEFINES_H_
#define __EXTERNALRMLDEFINES_H_

/* from: corbaimpl.cpp */
extern RML_FORWARD_LABEL(Corba__initialize);
extern RML_FORWARD_LABEL(Corba__wait_5ffor_5fcommand);
extern RML_FORWARD_LABEL(Corba__sendreply);
extern RML_FORWARD_LABEL(Corba__close);
#define Corba__waitForCommand Corba__wait_5ffor_5fcommand

/* from: corbaimpl_stub.cpp */
extern RML_FORWARD_LABEL(Corba__initialize);
extern RML_FORWARD_LABEL(Corba__wait_5ffor_5fcommand);
extern RML_FORWARD_LABEL(Corba__sendreply);
extern RML_FORWARD_LABEL(Corba__close);
#define Corba__waitForCommand Corba__wait_5ffor_5fcommand

/* daeext.cpp */  
extern RML_FORWARD_LABEL(DAEEXT__init_5fmarks);
#define DAEEXT__initMarks  DAEEXT__init_5fmarks
extern RML_FORWARD_LABEL(DAEEXT__e_5fmark);
#define DAEEXT__eMark DAEEXT__e_5fmark
extern RML_FORWARD_LABEL(DAEEXT__v_5fmark);
#define DAEEXT__vMark DAEEXT__v_5fmark
extern RML_FORWARD_LABEL(DAEEXT__get_5fv_5fmark);
#define DAEEXT__getVMark DAEEXT__get_5fv_5fmark
extern RML_FORWARD_LABEL(DAEEXT__get_5fe_5fmark);
#define DAEEXT__getEMark DAEEXT__get_5fe_5fmark
extern RML_FORWARD_LABEL(DAEEXT__get_5fmarked_5feqns);
#define DAEEXT__getMarkedEqns DAEEXT__get_5fmarked_5feqns
extern RML_FORWARD_LABEL(DAEEXT__get_5fmarked_5fvariables);
#define DAEEXT__getMarkedVariables DAEEXT__get_5fmarked_5fvariables
extern RML_FORWARD_LABEL(DAEEXT__init_5flowlink);
#define DAEEXT__initLowlink DAEEXT__init_5flowlink
extern RML_FORWARD_LABEL(DAEEXT__init_5fnumber);
#define DAEEXT__initNumber DAEEXT__init_5fnumber
extern RML_FORWARD_LABEL(DAEEXT__set_5flowlink);
#define DAEEXT__setLowlink DAEEXT__set_5flowlink
extern RML_FORWARD_LABEL(DAEEXT__set_5fnumber);
#define DAEEXT__setNumber DAEEXT__set_5fnumber
extern RML_FORWARD_LABEL(DAEEXT__get_5fnumber);
#define DAEEXT__getNumber DAEEXT__get_5fnumber
extern RML_FORWARD_LABEL(DAEEXT__get_5flowlink);
#define DAEEXT__getLowlink DAEEXT__get_5flowlink
extern RML_FORWARD_LABEL(DAEEXT__dump_5fmarked_5fequations);
#define DAEEXT__dumpMarkedEquations DAEEXT__dump_5fmarked_5fequations
extern RML_FORWARD_LABEL(DAEEXT__dump_5fmarked_5fvariables);
#define DAEEXT__dumpMarkedVariables DAEEXT__dump_5fmarked_5fvariables
extern RML_FORWARD_LABEL(DAEEXT__init_5fv);
#define DAEEXT__initV DAEEXT__init_5fv
extern RML_FORWARD_LABEL(DAEEXT__init_5ff);
#define DAEEXT__initF DAEEXT__init_5ff
extern RML_FORWARD_LABEL(DAEEXT__set_5ff);
#define DAEEXT__setF DAEEXT__set_5ff
extern RML_FORWARD_LABEL(DAEEXT__get_5ff);
#define DAEEXT__getF DAEEXT__get_5ff
extern RML_FORWARD_LABEL(DAEEXT__set_5fv);
#define DAEEXT__setV DAEEXT__set_5fv
extern RML_FORWARD_LABEL(DAEEXT__get_5fv);
#define DAEEXT__getV DAEEXT__get_5fv

/* from: errorext.cpp  */

extern RML_FORWARD_LABEL(ErrorExt__add_5fmessage);
#define ErrorExt__addMessage ErrorExt__add_5fmessage
extern RML_FORWARD_LABEL(ErrorExt__add_5fsource_5fmessage);
#define ErrorExt__addSourceMessage ErrorExt__add_5fsource_5fmessage
extern RML_FORWARD_LABEL(ErrorExt__print_5fmessages_5fstr);
#define ErrorExt__printMessagesStr ErrorExt__print_5fmessages_5fstr
extern RML_FORWARD_LABEL(ErrorExt__get_5fmessages_5fstr);
#define ErrorExt__getMessagesStr ErrorExt__get_5fmessages_5fstr
extern RML_FORWARD_LABEL(ErrorExt__error_5foff);
#define ErrorExt__errorOff ErrorExt__error_5foff 
extern RML_FORWARD_LABEL(ErrorExt__error_5fon);
#define ErrorExt__errorOn ErrorExt__error_5fon 

/* from: printimpl.c */
extern RML_FORWARD_LABEL(Print__print_5ferror_5fbuf);
#define Print__printErrorBuf Print__print_5ferror_5fbuf
extern RML_FORWARD_LABEL(Print__clear_5ferror_5fbuf);
#define Print__clearErrorBuf Print__clear_5ferror_5fbuf
extern RML_FORWARD_LABEL(Print__get_5ferror_5fstring);
#define Print__getErrorString Print__get_5ferror_5fstring
extern RML_FORWARD_LABEL(Print__print_5fbuf);
#define Print__printBuf Print__print_5fbuf 
extern RML_FORWARD_LABEL(Print__clear_5fbuf);
#define Print__clearBuf Print__clear_5fbuf 
extern RML_FORWARD_LABEL(Print__get_5fstring);
#define Print__getString Print__get_5fstring 
extern RML_FORWARD_LABEL(Print__write_5fbuf);
#define Print__writeBuf Print__write_5fbuf 

/* from: rtopts.c */
extern RML_FORWARD_LABEL(RTOpts__args);
extern RML_FORWARD_LABEL(RTOpts__typeinfo);
extern RML_FORWARD_LABEL(RTOpts__split_5farrays);
#define RTOpts__splitArrays RTOpts__split_5farrays 
extern RML_FORWARD_LABEL(RTOpts__modelica_5foutput);
#define RTOpts__modelicaOutput RTOpts__modelica_5foutput
extern RML_FORWARD_LABEL(RTOpts__params_5fstruct);
#define RTOpts__paramsStruct RTOpts__params_5fstruct 
extern RML_FORWARD_LABEL(RTOpts__silent);
extern RML_FORWARD_LABEL(RTOpts__debug_5fflag);
#define RTOpts__debugFlag RTOpts__debug_5fflag
extern RML_FORWARD_LABEL(RTOpts__no_5fproc);
#define RTOpts__noProc RTOpts__no_5fproc
extern RML_FORWARD_LABEL(RTOpts__latency);
extern RML_FORWARD_LABEL(RTOpts__bandwidth);
extern RML_FORWARD_LABEL(RTOpts__simulation_5fcg);
#define RTOpts__simulationCg RTOpts__simulation_5fcg

/* from: socketimpl.c */
extern RML_FORWARD_LABEL(Socket__waitforconnect);
extern RML_FORWARD_LABEL(Socket__handlerequest);
extern RML_FORWARD_LABEL(Socket__close);
extern RML_FORWARD_LABEL(Socket__sendreply);
extern RML_FORWARD_LABEL(Socket__cleanup);

/* from: systemimpl.c: */

extern RML_FORWARD_LABEL(System__strtok);
extern RML_FORWARD_LABEL(System__toupper);
extern RML_FORWARD_LABEL(System__remove_5ffirst_5fand_5flast_5fchar);
#define System__removeFirstAndLastChar System__remove_5ffirst_5fand_5flast_5fchar
extern RML_FORWARD_LABEL(System__trim);
extern RML_FORWARD_LABEL(System__strcmp);
extern RML_FORWARD_LABEL(System__string_5freplace);
#define System__stringReplace System__string_5freplace
extern RML_FORWARD_LABEL(System__compile_5fc_5ffile);
#define System__compileCFile System__compile_5fc_5ffile
extern RML_FORWARD_LABEL(System__set_5fc_5fcompiler);
#define System__setCCompiler System__set_5fc_5fcompiler
extern RML_FORWARD_LABEL(System__set_5fc_5fflags);
#define System__setCFlags System__set_5fc_5fflags 
extern RML_FORWARD_LABEL(System__execute_5ffunction);
#define System__executeFunction System__execute_5ffunction 
extern RML_FORWARD_LABEL(System__system_5fcall);
#define System__systemCall System__system_5fcall
extern RML_FORWARD_LABEL(System__cd);
extern RML_FORWARD_LABEL(System__pwd);
extern RML_FORWARD_LABEL(System__write_5ffile);
#define System__writeFile System__write_5ffile 
extern RML_FORWARD_LABEL(System__read_5ffile);
#define System__readFile System__read_5ffile 
extern RML_FORWARD_LABEL(System__modelicapath);
extern RML_FORWARD_LABEL(System__read_5fenv);
#define System__readEnv System__read_5fenv
extern RML_FORWARD_LABEL(System__set_5fenv);
#define System__setEnv System__set_5fenv
extern RML_FORWARD_LABEL(System__sub_5fdirectories);
#define System__subDirectories System__sub_5fdirectories
extern RML_FORWARD_LABEL(System__mo_5ffiles);
#define System__moFiles System__mo_5ffiles

extern RML_FORWARD_LABEL(System__read_5fvalues_5ffrom_5ffile);
#define System__readValuesFromFile System__read_5fvalues_5ffrom_5ffile
extern RML_FORWARD_LABEL(System__read_5fptolemyplot_5fdataset);
#define System__readPtolemyplotDataset System__read_5fptolemyplot_5fdataset
extern RML_FORWARD_LABEL(System__read_5fptolemyplot_5fdataset_5fsize);
#define System__readPtolemyplotDatasetSize System__read_5fptolemyplot_5fdataset_5fsize
extern RML_FORWARD_LABEL(System__write_5fptolemyplot_5fdataset);
#define System__writePtolemyplotDataset System__write_5fptolemyplot_5fdataset
extern RML_FORWARD_LABEL(System__time);
extern RML_FORWARD_LABEL(System__hash);
extern RML_FORWARD_LABEL(System__path_5fdelimiter);
#define System__pathDelimiter System__path_5fdelimiter
extern RML_FORWARD_LABEL(System__group_5fdelimiter);
#define System__groupDelimiter System__group_5fdelimiter
extern RML_FORWARD_LABEL(System__directory_5fexist);
#define System__directoryExist System__directory_5fexist
extern RML_FORWARD_LABEL(System__regular_5ffile_5fexist);
#define System__regularFileExist System__regular_5ffile_5fexist
extern RML_FORWARD_LABEL(System__platform);
extern RML_FORWARD_LABEL(System__asin);
extern RML_FORWARD_LABEL(System__acos);
extern RML_FORWARD_LABEL(System__atan);
extern RML_FORWARD_LABEL(System__atan2);
extern RML_FORWARD_LABEL(System__cosh);
extern RML_FORWARD_LABEL(System__log);
extern RML_FORWARD_LABEL(System__log10);
extern RML_FORWARD_LABEL(System__sinh);
extern RML_FORWARD_LABEL(System__tanh);
extern RML_FORWARD_LABEL(System__get_5fclassnames_5ffor_5fsimulation);
#define System__getClassnamesForSimulation System__get_5fclassnames_5ffor_5fsimulation 
extern RML_FORWARD_LABEL(System__set_5fclassnames_5ffor_5fsimulation);
#define System__setClassnamesForSimulation System__set_5fclassnames_5ffor_5fsimulation 
extern RML_FORWARD_LABEL(System__set_5fcompile_5fcommand);
#define System__setCompileCommand System__set_5fcompile_5fcommand
extern RML_FORWARD_LABEL(System__get_5fcompile_5fcommand);
#define System__getCompileCommand System__get_5fcompile_5fcommand

/* taskgraphext.c */
extern RML_FORWARD_LABEL(TaskGraphExt__new_5ftask);
#define TaskGraphExt__newTask TaskGraphExt__new_5ftask
extern RML_FORWARD_LABEL(TaskGraphExt__add_5fedge);
#define TaskGraphExt__addEdge TaskGraphExt__add_5fedge
extern RML_FORWARD_LABEL(TaskGraphExt__get_5ftask);
#define TaskGraphExt__getTask TaskGraphExt__get_5ftask
extern RML_FORWARD_LABEL(TaskGraphExt__store_5fresult);
#define TaskGraphExt__storeResult TaskGraphExt__store_5fresult
extern RML_FORWARD_LABEL(TaskGraphExt__dump_5fgraph);
#define TaskGraphExt__dumpGraph TaskGraphExt__dump_5fgraph
extern RML_FORWARD_LABEL(TaskGraphExt__dump_5fmerged_5fgraph);
#define TaskGraphExt__dumpMergedGraph TaskGraphExt__dump_5fmerged_5fgraph
extern RML_FORWARD_LABEL(TaskGraphExt__register_5fstartstop);
#define TaskGraphExt__registerStartstop TaskGraphExt__register_5fstartstop
extern RML_FORWARD_LABEL(TaskGraphExt__get_5fstarttask);
#define TaskGraphExt__getStarttask TaskGraphExt__get_5fstarttask
extern RML_FORWARD_LABEL(TaskGraphExt__get_5fstoptask);
#define TaskGraphExt__getStoptask TaskGraphExt__get_5fstoptask
extern RML_FORWARD_LABEL(TaskGraphExt__merge_5ftasks);
#define TaskGraphExt__mergeTasks TaskGraphExt__merge_5ftasks
extern RML_FORWARD_LABEL(TaskGraphExt__set_5fexeccost);
#define TaskGraphExt__setExeccost TaskGraphExt__set_5fexeccost
extern RML_FORWARD_LABEL(TaskGraphExt__set_5fcommcost);
#define TaskGraphExt__setCommcost TaskGraphExt__set_5fcommcost
extern RML_FORWARD_LABEL(TaskGraphExt__schedule);
extern RML_FORWARD_LABEL(TaskGraphExt__generate_5fcode);
#define TaskGraphExt__generateCode TaskGraphExt__generate_5fcode
extern RML_FORWARD_LABEL(TaskGraphExt__add_5finitvar);
#define TaskGraphExt__addInitvar TaskGraphExt__add_5finitvar
extern RML_FORWARD_LABEL(TaskGraphExt__add_5finitstate);
#define TaskGraphExt__addInitstate TaskGraphExt__add_5finitstate
extern RML_FORWARD_LABEL(TaskGraphExt__add_5finitparam);
#define TaskGraphExt__addInitparam TaskGraphExt__add_5finitparam
extern RML_FORWARD_LABEL(TaskGraphExt__set_5ftasktype);
#define TaskGraphExt__setTasktype TaskGraphExt__set_5ftasktype

#endif /* __EXTERNALRMLDEFINES_H_ */
