# Test 1
add_executable(test_string_vector_to_string
  01_test_string_vector_to_string.c
)
target_link_libraries(test_string_vector_to_string PRIVATE SimulationRuntimeC)
add_test(NAME test_string_vector_to_string COMMAND test_string_vector_to_string)

add_custom_target(ctestsuite-util-string_array DEPENDS
  test_string_vector_to_string
)
