# This file sets the basic flags for the MODELICA compiler
if(NOT CMAKE_MODELICA_COMPILE_OBJECT)
    set(CMAKE_MODELICA_COMPILE_OBJECT "<CMAKE_MODELICA_COMPILER> -g=MetaModelica -n=1 --locale=en <SOURCE>")
    set(CMAKE_MODELICA_COMPILE_DEPENDENCY_DETECTION
    "<CMAKE_MODELICA_COMPILER> -g=MetaModelica -n=1 --locale=en <SOURCE> > $DEP_FILE")
    list(APPEND CMAKE_MODELICA_COMPILE_OBJECT "${CMAKE_MODELICA_COMPILE_DEPENDENCY_DETECTION}")
endif()
set(CMAKE_MODELICA_INFORMATION_LOADED 1)
