// Hand-maintained: NOT generated by mmtorust.
//
// Rust port of `OMCompiler/Compiler/SimCode/SerializeSparsityPattern.mo`.
// The package serializes each Jacobian's sparsity pattern and coloring to
// `<fileNamePrefix>_Jac<matrixName>.bin` next to the generated simulation
// code; the simulation runtime reads the file back when the Jacobian is
// evaluated.  Its two `external "C"` functions (`serializeJ`, `serializeC`)
// exist only as inline C snippets inside the .mo's `Include` annotation, so
// mmtorust could only emit `todo!()` for them — this module is hand-written
// and `SerializeSparsityPattern` is listed in `HANDWRITTEN_TOP_PACKAGES`
// (mmtorust/src/codegen.rs) to skip its codegen.
//
// File format (mirroring the C snippets exactly): a flat sequence of
// native-endian `unsigned int`s —
//
//   1. the leadindex: for each entry of `columnPointers` (a leading 0
//      followed by the per-column non-zero counts), the running sum so far;
//   2. the row index of every non-zero, column by column;
//   3. appended afterwards, one block per color: the column indices of that
//      color.
//
// We use `u32::to_ne_bytes` because the C version `fwrite`s raw
// `unsigned int` memory and the file is consumed by the simulation runtime
// on the same machine.  The C version throws via `throwStreamPrint` on
// open/write failures; here the writers return `Result` instead (their
// registry entries in mmtorust/src/external_c_calls.rs are `Fallible`).

/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
 * THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */
#![allow(non_snake_case)]

use std::io::Write;

use anyhow::{bail, Context, Result};
use arcstr::{literal, ArcStr};
use metamodelica::{list, List};

use openmodelica_simcode_types::SimCode;
use openmodelica_util::Error;

pub fn serialize(code: SimCode::SimCode) -> Result<ArcStr> {
    for jac in &*code.jacobianMatrices {
        // Pick sparsity and coloring depending on the isAdjoint flag.
        let (pattern, colorList) = if jac.isAdjoint {
            // For the adjoint Jacobian a row coloring must exist.
            if matches!(&*jac.coloredRows, List::Nil) {
                Error::addMessage(
                    Error::INTERNAL_ERROR.clone(),
                    list![literal!(
                        "SerializeSparsityPattern.serialize failed because no row coloring for the adjoint jacobian exists."
                    )],
                )?;
                bail!("fail");
            }
            (&jac.sparsityT, &jac.coloredRows)
        } else {
            (&jac.sparsity, &jac.coloredCols)
        };

        if matches!(&**pattern, List::Nil) {
            continue;
        }

        let fname = format!("{}_Jac{}.bin", code.fileNamePrefix, jac.matrixName);
        // columnPointers = 0 :: per-column non-zero counts; rowIndices =
        // the concatenation of every column's row-index list (matching the
        // `listArray(...)` constructions in the .mo).
        let mut colPtrs: Vec<i32> = vec![0];
        let mut rowInds: Vec<i32> = Vec::new();
        for (_, rows) in &**pattern {
            colPtrs.push(rows.len());
            rowInds.extend((&**rows).into_iter().copied());
        }
        serializeJacobian(&fname, &colPtrs, &rowInds)?;
        for color in &**colorList {
            let columns: Vec<i32> = (&**color).into_iter().copied().collect();
            serializeColor(&fname, &columns)?;
        }
    }
    Ok(literal!(""))
}

// *********************
// write to binary stuff
// *********************

/// `serializeJ` from the .mo `Include` annotation: create `name` ("wb") and
/// write the leadindex (the running sum over `colPtrs`) followed by the row
/// indices, each as a native-endian u32.
fn serializeJacobian(name: &str, colPtrs: &[i32], rowInds: &[i32]) -> Result<()> {
    let file = std::fs::File::create(name)
        .with_context(|| format!("Could not open sparsity pattern file {name}."))?;
    let mut out = std::io::BufWriter::new(file);
    // Compute and write sparsePattern->leadindex.
    let mut j: u32 = 0;
    for &c in colPtrs {
        j = j.wrapping_add(c as u32);
        out.write_all(&j.to_ne_bytes())
            .with_context(|| format!("Error while writing sparsePattern->leadindex to {name}."))?;
    }
    // Write sparsePattern->index.
    for &r in rowInds {
        out.write_all(&(r as u32).to_ne_bytes())
            .with_context(|| format!("Error while writing sparsePattern->index to {name}."))?;
    }
    out.flush()
        .with_context(|| format!("Error while writing sparsity pattern file {name}."))?;
    Ok(())
}

/// `serializeC` from the .mo `Include` annotation: append ("ab") one color's
/// column indices to the pattern file, each as a native-endian u32.
fn serializeColor(name: &str, columns: &[i32]) -> Result<()> {
    let file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(name)
        .with_context(|| format!("Could not open sparsity pattern file {name}."))?;
    let mut out = std::io::BufWriter::new(file);
    // Write sparsePattern->colorCols.
    for &c in columns {
        out.write_all(&(c as u32).to_ne_bytes())
            .with_context(|| format!("Error while writing sparsePattern->colorCols to {name}."))?;
    }
    out.flush()
        .with_context(|| format!("Error while writing sparsity pattern file {name}."))?;
    Ok(())
}
