# Cross-compile OpenModelica's C/C++ to *-apple-darwin from Linux with `zig cc`
# and a copy of the macOS SDK, matching what cargo-zigbuild does for the Rust
# artifacts (so the two are ABI-compatible). No Xcode, no macOS host and no
# cctools: the SDK's .tbd stubs are all zig's linker needs.
#
#   cmake -S . -B build-mac \
#     -DCMAKE_TOOLCHAIN_FILE=OMCompiler/Compiler/OpenModelica.rs/.cmake/darwin-toolchain.cmake \
#     -DDARWIN_SDK=/path/to/MacOSX15.5.sdk [-DDARWIN_ARCH=x86_64]
#
# See OpenModelica.rs/README.md for usage + setup.

set(CMAKE_SYSTEM_NAME Darwin)

# arm64 by default; x86_64 for the Intel build. CMake spells arm64 "arm64" and
# zig spells it "aarch64".
if(NOT DARWIN_ARCH)
  set(DARWIN_ARCH arm64)
endif()
if(DARWIN_ARCH STREQUAL "arm64" OR DARWIN_ARCH STREQUAL "aarch64")
  set(CMAKE_SYSTEM_PROCESSOR arm64)
  set(_darwin_zig_arch aarch64)
  set(_darwin_triple aarch64-apple-darwin)
else()
  set(CMAKE_SYSTEM_PROCESSOR x86_64)
  set(_darwin_zig_arch x86_64)
  set(_darwin_triple x86_64-apple-darwin)
endif()

# The SDK: -DDARWIN_SDK / $DARWIN_SDK / $SDKROOT, else the newest MacOSX*.sdk
# beside the checkout (where the Jenkins bind-mount puts it).
if(NOT DARWIN_SDK)
  if(DEFINED ENV{DARWIN_SDK})
    set(DARWIN_SDK "$ENV{DARWIN_SDK}")
  elseif(DEFINED ENV{SDKROOT})
    set(DARWIN_SDK "$ENV{SDKROOT}")
  else()
    file(GLOB _sdks "${CMAKE_CURRENT_LIST_DIR}/../../../../../MacOSX*.sdk" "/mnt/MacOSX*.sdk")
    list(SORT _sdks)
    list(REVERSE _sdks)
    list(LENGTH _sdks _n)
    if(_n GREATER 0)
      list(GET _sdks 0 DARWIN_SDK)
    endif()
  endif()
endif()
if(NOT EXISTS "${DARWIN_SDK}/usr/include/stdio.h")
  message(FATAL_ERROR
    "macOS SDK not found at '${DARWIN_SDK}'. Pass -DDARWIN_SDK=<MacOSX*.sdk> "
    "(or set DARWIN_SDK / SDKROOT).")
endif()
set(CMAKE_OSX_SYSROOT "${DARWIN_SDK}" CACHE PATH "macOS SDK to compile against.")
# The SDK's own macOS version. Only needs to be non-empty: some 3rdParty CMake
# dereferences CMAKE_SYSTEM_VERSION unquoted, which malforms the if() when it is
# not set (3rdParty/libzmq), and cross-compiling leaves it empty.
if(NOT CMAKE_SYSTEM_VERSION)
  set(CMAKE_SYSTEM_VERSION 26.0)
  if(EXISTS "${DARWIN_SDK}/SDKSettings.json")
    file(READ "${DARWIN_SDK}/SDKSettings.json" _sdk_settings)
    string(JSON _sdk_version ERROR_VARIABLE _ignored GET "${_sdk_settings}" "Version")
    if(_sdk_version)
      set(CMAKE_SYSTEM_VERSION "${_sdk_version}")
    endif()
  endif()
endif()
# The SDK decides what is available; asking CMake to also police a minimum
# version only adds -mmacosx-version-min, which zig sets from the triple.
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "" FORCE)

# `zig cc` is two words, so CMake needs a one-word driver: generate wrappers.
# ZIG_EXECUTABLE / $ZIG wins; else `zig` on PATH, else the ziglang Python
# package's own binary (pip install ziglang).
if(NOT ZIG_EXECUTABLE)
  if(DEFINED ENV{ZIG})
    set(ZIG_EXECUTABLE "$ENV{ZIG}")
  else()
    find_program(ZIG_EXECUTABLE zig)
  endif()
endif()
if(NOT ZIG_EXECUTABLE)
  execute_process(COMMAND python3 -c "import ziglang,os;print(os.path.join(os.path.dirname(ziglang.__file__),'zig'))"
                  OUTPUT_VARIABLE _zig_py OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(_zig_py AND EXISTS "${_zig_py}")
    set(ZIG_EXECUTABLE "${_zig_py}")
  endif()
endif()
if(NOT ZIG_EXECUTABLE)
  message(FATAL_ERROR "zig not found. Install it, `pip install ziglang`, or pass -DZIG_EXECUTABLE=<path>.")
endif()

# Written beside the cache, so a try_compile subproject regenerates its own.
set(_darwin_wrappers "${CMAKE_BINARY_DIR}/darwin-toolchain")
foreach(_w cc c++)
  if(_w STREQUAL "cc")
    set(_out "${_darwin_wrappers}/zig-cc")
  else()
    set(_out "${_darwin_wrappers}/zig-c++")
  endif()
  # `--sysroot` for the headers and libraries, plus the framework path it does
  # not imply (3rdParty/gc's darwin_stop_world.c includes CoreFoundation).
  # Both as *system* paths: naming the SDK's include dir with `-I`/`-F` instead
  # would make its headers user headers, and warnings then fire inside them --
  # the SDK trips -Wpedantic and -Wc23-extensions, which the C runtime builds
  # with as errors. An explicit -L is worse still: it resolves relative to the
  # sysroot rather than to /.
  file(WRITE "${_out}"
"#!/bin/sh
# Generated by darwin-toolchain.cmake.
exec \"${ZIG_EXECUTABLE}\" ${_w} -target ${_darwin_zig_arch}-macos --sysroot \"${DARWIN_SDK}\" \\
  -iframework \"${DARWIN_SDK}/System/Library/Frameworks\" \"$@\"
")
  file(CHMOD "${_out}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE)
endforeach()

set(CMAKE_C_COMPILER "${_darwin_wrappers}/zig-cc")
set(CMAKE_CXX_COMPILER "${_darwin_wrappers}/zig-c++")
# Deliberately no CMAKE_<LANG>_COMPILER_TARGET: it would add clang's
# `--target=aarch64-apple-darwin`, which zig rejects (it spells the same target
# `aarch64-macos`, which the wrapper already passes).
# zig ships the archiver and the Mach-O strip/ranlib, so no cctools are needed.
set(CMAKE_AR "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_C_COMPILER_AR "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_AR "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_RANLIB "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_C_COMPILER_RANLIB "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER_RANLIB "${ZIG_EXECUTABLE}" CACHE FILEPATH "")
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> ar qc <TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> ar q <TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> ranlib <TARGET>")
set(CMAKE_CXX_ARCHIVE_CREATE "${CMAKE_C_ARCHIVE_CREATE}")
set(CMAKE_CXX_ARCHIVE_APPEND "${CMAKE_C_ARCHIVE_APPEND}")
set(CMAKE_CXX_ARCHIVE_FINISH "${CMAKE_C_ARCHIVE_FINISH}")

# The Mach-O tools CMake and 3rdParty reach for by their Apple names, which a
# Linux host has only as LLVM's drop-in equivalents: `libtool -static` merges
# static archives (3rdParty/FMIL), and install_name_tool/otool are what CMake
# rewrites install rpaths with. Set in the cache so the find_program()s that
# want them (which search host paths, since the SDK has no binaries) stop early.
foreach(_tool libtool:LIBTOOL install-name-tool:INSTALL_NAME_TOOL otool:OTOOL)
  string(REPLACE ":" ";" _tool "${_tool}")
  list(GET _tool 0 _name)
  list(GET _tool 1 _var)
  # A previous configure may have cached the failed find as `<VAR>-NOTFOUND`, so
  # the answer has to be FORCEd in; a value the user set is left alone.
  if(NOT CMAKE_${_var})
    set(_found "")
    # Some distributions ship these only under a version suffix.
    file(GLOB _cand "/usr/bin/llvm-${_name}-darwin" "/usr/bin/llvm-${_name}-darwin-*"
                    "/usr/bin/llvm-${_name}" "/usr/bin/llvm-${_name}-*")
    if(_cand)
      list(SORT _cand)
      list(REVERSE _cand)
      list(GET _cand 0 _found)
    endif()
    if(_found)
      set(CMAKE_${_var} "${_found}" CACHE FILEPATH "Mach-O ${_name} for the cross build." FORCE)
    endif()
  endif()
endforeach()

# Look for headers and libraries in the SDK, and programs on the host.
set(CMAKE_FIND_ROOT_PATH "${DARWIN_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
