.\" --------------------------------------------------------------------
.\" Title
.\" --------------------------------------------------------------------
.
.TH OMShell 1 "" "OpenModelica @OM_MANPAGE_VERSION@" "OpenModelica User Commands"
.
.\" --------------------------------------------------------------------
.SH NAME
.\" --------------------------------------------------------------------
.
OMShell \- interactive OpenModelica shell in a window
.
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.
.B OMShell
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B OMShell
is a graphical window in which OpenModelica scripting commands are typed and
evaluated one at a time, with command history and completion. Type
.B help()
for an overview of the commands.
.PP
It links the OpenModelica compiler in rather than starting
.BR omc .
.PP
The working directory is
.I OpenModelica
in the temporary directory, usually
.IR /tmp/OpenModelica ,
so that generated code and result files do not clutter the directory it was
started from.
.
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.\" --------------------------------------------------------------------
.
.TP
.B TMPDIR
The temporary directory the working directory is created in. The default is
.IR /tmp .
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR omc (1),
.BR OMShell\-terminal (1),
.BR OMNotebook (1)
.
.\" --------------------------------------------------------------------
.SH BUGS
.\" --------------------------------------------------------------------
.
Report bugs at <https://github.com/OpenModelica/OpenModelica/issues>.
.
.\" --------------------------------------------------------------------
.SH AUTHOR
.\" --------------------------------------------------------------------
.
Open Source Modelica Consortium (OSMC), <https://www.openmodelica.org>
