.\" --------------------------------------------------------------------
.\" Title 
.\" --------------------------------------------------------------------
.
.TH OMShell 1 "The Open Source Modelica Consortium" "1.7.0" "The OpenModelica Project" -*- nroff -*-
.
.
.\" -------------------------------------------------------------------- 
.SH NAME
.\" --------------------------------------------------------------------
.
OMShell \- A command-line shell for OpenModelica
.
.
.\" --------------------------------------------------------------------
.SH "SYNOPSIS"
.\" --------------------------------------------------------------------
.
.B OMShell
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B OMShell
is a command-line interface to communicate with \fBomc\fP using CORBA.
.P
The default working directory is /tmp/OpenModelica/.
This is to avoid \fBomc\fP producing its C++ source code and auxiliary
files in the working directory.
.
.\" --------------------------------------------------------------------
.SH AUTHOR
.\" --------------------------------------------------------------------
.
See OpenModelicaUsersGuide.pdf for a full list of contributors to the
\%OpenModelica project.
.
.\" --------------------------------------------------------------------
.SH BUGS
.\" --------------------------------------------------------------------
.
If you find a bug, please report it at:
.P
<\fBhttp://openmodelica.org:8080/cb/project/1\fR>
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR omc (1),
.BR OMShell (1),
.BR OMShell\-terminal (1)
.
