# Peter Aronsson MathCore Engineering AB
# Peter.aronsson@mathcore.com

INCLUDES = $(INCP) /I. /I..\..\SimulationRuntime\c\ /I..\

CFLAGS = /O2 /Ot $(INCLUDES) /D "WIN32" /D "NDEBUG" /D "_LIB"  /D "_MBCS" /FD /EHsc /MT /GS- /W2 /c /TC
CXXFLAGS = /O2 /Ot $(INCLUDES) /D "WIN32" /D "NDEBUG" /D "_LIB"  /D "_MBCS" /FD /EHsc /MT /GS- /W2 /c /TP

SHELL	= /bin/sh
CC	= cl

OBJ = socketimpl.obj printimpl.obj systemimpl.obj systemimplmisc.obj dynload.obj dynload_try.obj settingsimpl.obj \
ptolemyio.obj ASSCEXT.obj BackendDAEEXT.obj ErrorMessage.obj errorext.obj \
unitparser.obj unitparserext.obj SimulationResults.obj IOStreamExt.obj rtclock.obj

all: $(OBJ) runtimevc.lib

runtimevc.lib: $(OBJ)
	LIB /out:runtimevc.lib $(OBJ)

.cpp.obj:
	$(CC) $(CXXFLAGS) $<

.c.obj:
	$(CC) $(CFLAGS) $<

.cc.obj:
	$(CC) $(CXXFLAGS) $<


clean:
	del  *.obj


