/*
 * This file is part of OpenModelica.
 *
 * Copyright (c) 1998-2008, Linköpings University,
 * Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF THIS OSMC PUBLIC
 * LICENSE (OSMC-PL). ANY USE, REPRODUCTION OR DISTRIBUTION OF
 * THIS PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THE OSMC
 * PUBLIC LICENSE.
 *
 * The OpenModelica software and the Open Source Modelica
 * Consortium (OSMC) Public License (OSMC-PL) are obtained
 * from Linköpings University, either from the above address,
 * from the URL: http://www.ida.liu.se/projects/OpenModelica
 * and in the OpenModelica distribution.
 *
 * This program is distributed  WITHOUT ANY WARRANTY; without
 * even the implied warranty of  MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE, EXCEPT AS EXPRESSLY SET FORTH
 * IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE CONDITIONS
 * OF OSMC-PL.
 *
 * See the full OSMC Public License conditions for more details.
 *
 */

package Constants
" file:	       Constants.mo
  package:     Constants
  description: definition of a set of constants

  RCS: $Id$

  Constants defined in here (Constants.mo) are used in Interactive.mo"

import Absyn;

public constant Absyn.Program graphicsProgram=Absyn.PROGRAM(
          {
          Absyn.CLASS("LinePattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Dash",NONE),Absyn.ENUMLITERAL("Dot",NONE),
          Absyn.ENUMLITERAL("DashDot",NONE),Absyn.ENUMLITERAL("DashDot",NONE),
          Absyn.ENUMLITERAL("DashDotDot",NONE)}),NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Arrow",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Open",NONE),Absyn.ENUMLITERAL("Filled",NONE),Absyn.ENUMLITERAL("Filled",NONE),
          Absyn.ENUMLITERAL("Half",NONE)}),NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("FillPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Horizontal",NONE),
          Absyn.ENUMLITERAL("Vertical",NONE),Absyn.ENUMLITERAL("Cross",NONE),Absyn.ENUMLITERAL("Forward",NONE),
          Absyn.ENUMLITERAL("Backward",NONE),Absyn.ENUMLITERAL("CrossDiag",NONE),
          Absyn.ENUMLITERAL("HorizontalCylinder",NONE),Absyn.ENUMLITERAL("VerticalCylinder",NONE),
          Absyn.ENUMLITERAL("VerticalCylinder",NONE),Absyn.ENUMLITERAL("Sphere",NONE)}),NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("BorderPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Raised",NONE),Absyn.ENUMLITERAL("Sunken",NONE),Absyn.ENUMLITERAL("Sunken",NONE),
          Absyn.ENUMLITERAL("Engraved",NONE)}),NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("TextStyle",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("Bold",NONE),
          Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Underline",NONE)}),NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Line",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("color",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("thickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Arrow"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrow",{Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{}))),Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{})))}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrowSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(3.0))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,6,0,6,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Polygon",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,7,0,7,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Rectangle",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("BorderPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("borderPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("BorderPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("radius",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,8,0,8,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Ellipse",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,9,0,9,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Text",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textString",{},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("TextStyle"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textStyle",{Absyn.NOSUB()},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,10,0,10,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("Bitmap",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("graphics.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fileName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("imageSource",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("graphics.mo",true,11,0,11,0),NONE))})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("graphics.mo",true,0,0,0,0))},Absyn.TOP()) "AST for the builtin graphical classes" ;

public constant Absyn.Program iconProgram=Absyn.PROGRAM(
          {
          Absyn.CLASS("GraphicItem",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("CoordinateSystem",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Icon",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("CoordinateSystem"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("coordinateSystem",{},
          SOME(
          Absyn.CLASSMOD(
          {
          Absyn.MODIFICATION(false,Absyn.NON_EACH(),Absyn.CREF_IDENT("extent",{}),
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.ARRAY(
          {Absyn.UNARY(Absyn.UMINUS(),Absyn.REAL(10.0)),
          Absyn.UNARY(Absyn.UMINUS(),Absyn.REAL(10.0))}),Absyn.ARRAY({Absyn.REAL(10.0),Absyn.REAL(10.0)})})))),NONE)},NONE))),NONE,NONE)}),Absyn.INFO("icon.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("LinePattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Dash",NONE),Absyn.ENUMLITERAL("Dot",NONE),
          Absyn.ENUMLITERAL("DashDot",NONE),Absyn.ENUMLITERAL("DashDot",NONE),
          Absyn.ENUMLITERAL("DashDotDot",NONE)}),NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Arrow",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Open",NONE),Absyn.ENUMLITERAL("Filled",NONE),Absyn.ENUMLITERAL("Filled",NONE),
          Absyn.ENUMLITERAL("Half",NONE)}),NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("FillPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Horizontal",NONE),
          Absyn.ENUMLITERAL("Vertical",NONE),Absyn.ENUMLITERAL("Cross",NONE),Absyn.ENUMLITERAL("Forward",NONE),
          Absyn.ENUMLITERAL("Backward",NONE),Absyn.ENUMLITERAL("CrossDiag",NONE),
          Absyn.ENUMLITERAL("HorizontalCylinder",NONE),Absyn.ENUMLITERAL("VerticalCylinder",NONE),
          Absyn.ENUMLITERAL("VerticalCylinder",NONE),Absyn.ENUMLITERAL("Sphere",NONE)}),NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("BorderPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Raised",NONE),Absyn.ENUMLITERAL("Sunken",NONE),Absyn.ENUMLITERAL("Sunken",NONE),
          Absyn.ENUMLITERAL("Engraved",NONE)}),NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("TextStyle",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("Bold",NONE),
          Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Underline",NONE)}),NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Line",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("color",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("thickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Arrow"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrow",{Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{}))),Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{})))}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrowSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(3.0))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,8,0,8,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Polygon",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,9,0,9,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Rectangle",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("BorderPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("borderPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("BorderPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("radius",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,10,0,10,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Ellipse",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,11,0,11,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Text",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textString",{},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("TextStyle"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textStyle",{Absyn.NOSUB()},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,12,0,12,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("Bitmap",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("icon.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fileName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("imageSource",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("icon.mo",true,13,0,13,0),NONE))})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("icon.mo",true,0,0,0,0))},Absyn.TOP());

public constant Absyn.Program diagramProgram=Absyn.PROGRAM(
          {
          Absyn.CLASS("GraphicItem",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("CoordinateSystem",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Diagram",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("CoordinateSystem"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("coordinateSystem",{},
          SOME(
          Absyn.CLASSMOD(
          {
          Absyn.MODIFICATION(false,Absyn.NON_EACH(),Absyn.CREF_IDENT("extent",{}),
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.ARRAY(
          {Absyn.UNARY(Absyn.UMINUS(),Absyn.REAL(100.0)),
          Absyn.UNARY(Absyn.UMINUS(),Absyn.REAL(100.0))}),Absyn.ARRAY({Absyn.REAL(100.0),Absyn.REAL(100.0)})})))),NONE)},NONE))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("LinePattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Dash",NONE),Absyn.ENUMLITERAL("Dot",NONE),
          Absyn.ENUMLITERAL("DashDot",NONE),Absyn.ENUMLITERAL("DashDot",NONE),
          Absyn.ENUMLITERAL("DashDotDot",NONE)}),NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Arrow",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Open",NONE),Absyn.ENUMLITERAL("Filled",NONE),Absyn.ENUMLITERAL("Filled",NONE),
          Absyn.ENUMLITERAL("Half",NONE)}),NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("FillPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Horizontal",NONE),
          Absyn.ENUMLITERAL("Vertical",NONE),Absyn.ENUMLITERAL("Cross",NONE),Absyn.ENUMLITERAL("Forward",NONE),
          Absyn.ENUMLITERAL("Backward",NONE),Absyn.ENUMLITERAL("CrossDiag",NONE),
          Absyn.ENUMLITERAL("HorizontalCylinder",NONE),Absyn.ENUMLITERAL("VerticalCylinder",NONE),
          Absyn.ENUMLITERAL("VerticalCylinder",NONE),Absyn.ENUMLITERAL("Sphere",NONE)}),NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("BorderPattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Raised",NONE),Absyn.ENUMLITERAL("Sunken",NONE),Absyn.ENUMLITERAL("Sunken",NONE),
          Absyn.ENUMLITERAL("Engraved",NONE)}),NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("TextStyle",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("Bold",NONE),
          Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Italic",NONE),Absyn.ENUMLITERAL("Underline",NONE)}),NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Line",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("color",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("thickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Arrow"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrow",{Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{}))),Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{})))}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrowSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(3.0))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,8,0,8,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Polygon",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,9,0,9,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Rectangle",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("BorderPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("borderPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("BorderPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("radius",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,10,0,10,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Ellipse",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,11,0,11,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Text",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillColor",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("FillPattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fillPattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("FillPattern",{},Absyn.CREF_IDENT("None",{}))))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("lineThickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textString",{},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fontName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("TextStyle"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("textStyle",{Absyn.NOSUB()},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,12,0,12,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("Bitmap",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("extent",
          {Absyn.SUBSCRIPT(Absyn.INTEGER(2)),
          Absyn.SUBSCRIPT(Absyn.INTEGER(2))},NONE),NONE,NONE)}),Absyn.INFO("diagram.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("fileName",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,13,0,13,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("String"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("imageSource",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.STRING(""))))),NONE,NONE)}),Absyn.INFO("diagram.mo",true,13,0,13,0),NONE))})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("diagram.mo",true,0,0,0,0))},Absyn.TOP());

public constant Absyn.Program lineProgram=Absyn.PROGRAM(
          {
          Absyn.CLASS("LinePattern",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Solid",NONE),Absyn.ENUMLITERAL("Dash",NONE),Absyn.ENUMLITERAL("Dot",NONE),
          Absyn.ENUMLITERAL("DashDot",NONE),Absyn.ENUMLITERAL("DashDot",NONE),
          Absyn.ENUMLITERAL("DashDotDot",NONE)}),NONE),Absyn.INFO("line.mo",true,0,0,0,0)),
          Absyn.CLASS("Arrow",false,false,false,Absyn.R_TYPE(),
          Absyn.ENUMERATION(
          Absyn.ENUMLITERALS(
          {Absyn.ENUMLITERAL("None",NONE),
          Absyn.ENUMLITERAL("Open",NONE),Absyn.ENUMLITERAL("Filled",NONE),Absyn.ENUMLITERAL("Filled",NONE),
          Absyn.ENUMLITERAL("Half",NONE)}),NONE),Absyn.INFO("line.mo",true,0,0,0,0)),
          Absyn.CLASS("Line",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("points",{Absyn.NOSUB(),Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          NONE),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Integer"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("color",{Absyn.SUBSCRIPT(Absyn.INTEGER(3))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY({Absyn.INTEGER(0),Absyn.INTEGER(0),Absyn.INTEGER(0)}))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("LinePattern"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("pattern",{},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.CREF(
          Absyn.CREF_QUAL("LinePattern",{},Absyn.CREF_IDENT("Solid",{}))))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("thickness",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.25))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Arrow"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrow",{Absyn.SUBSCRIPT(Absyn.INTEGER(2))},
          SOME(
          Absyn.CLASSMOD({},
          SOME(
          Absyn.ARRAY(
          {
          Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{}))),Absyn.CREF(Absyn.CREF_QUAL("Arrow",{},Absyn.CREF_IDENT("None",{})))}))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("arrowSize",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(3.0))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("smooth",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("line.mo",true,1,0,1,0),NONE))})},NONE),Absyn.INFO("line.mo",true,0,0,0,0)),
          Absyn.CLASS("test",false,false,false,Absyn.R_MODEL(),
          Absyn.PARTS({Absyn.PUBLIC({})},NONE),Absyn.INFO("line.mo",true,0,0,0,0))},Absyn.TOP());

public constant Absyn.Program placementProgram=Absyn.PROGRAM(
          {
          Absyn.CLASS("Transformation",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("x",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("y",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("scale",{},SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(1.0))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("aspectRatio",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(1.0))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("flipHorizontal",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("flipVertical",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(false))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Real"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("rotation",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.REAL(0.0))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE))})},NONE),Absyn.INFO("placement.mo",true,0,0,0,0)),
          Absyn.CLASS("Placement",false,false,false,Absyn.R_RECORD(),
          Absyn.PARTS(
          {
          Absyn.PUBLIC(
          {
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Boolean"),NONE),
          {
          Absyn.COMPONENTITEM(
          Absyn.COMPONENT("visible",{},
          SOME(Absyn.CLASSMOD({},SOME(Absyn.BOOL(true))))),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Transformation"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("transformation",{},NONE),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE)),
          Absyn.ELEMENTITEM(
          Absyn.ELEMENT(false,NONE,Absyn.UNSPECIFIED(),"component",
          Absyn.COMPONENTS(Absyn.ATTR(false,Absyn.VAR(),Absyn.BIDIR(),{}),
          Absyn.TPATH(Absyn.IDENT("Transformation"),NONE),
          {
          Absyn.COMPONENTITEM(Absyn.COMPONENT("iconTransformation",{},NONE),NONE,NONE)}),Absyn.INFO("placement.mo",true,2,0,2,0),NONE))})},NONE),Absyn.INFO("placement.mo",true,0,0,0,0))},Absyn.TOP());


end Constants;
