Open Source Modelica Consortium

Copyright © 1998-\ *CurrentYear*, Open Source Modelica Consortium
(OSMC), c/o Linköpings universitet, Department of Computer and
Information Science, SE-58183 Linköping, Sweden

All rights reserved.

THIS PROGRAM IS PROVIDED UNDER THE TERMS OF GPL VERSION 3 LICENSE OR
THIS OSMC PUBLIC LICENSE (OSMC-PL). ANY USE, REPRODUCTION OR
DISTRIBUTION OF THIS PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THE
OSMC PUBLIC LICENSE OR THE GPL VERSION 3, ACCORDING TO RECIPIENTS
CHOICE.

The OpenModelica software and the OSMC (Open Source Modelica Consortium)
Public License (OSMC-PL) are obtained from OSMC, either from the above
address, from the URLs: https://www.openmodelica.org or
http://www.ida.liu.se/projects/OpenModelica, and in the OpenModelica
distribution. GNU version 3 is obtained from:
http://www.gnu.org/copyleft/gpl.html.

This program is distributed WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
EXCEPT AS EXPRESSLY SET FORTH IN THE BY RECIPIENT SELECTED SUBSIDIARY
LICENSE CONDITIONS OF OSMC-PL.

See the full OSMC Public License conditions for more details.

| This document is part of OpenModelica: https://www.openmodelica.org
| Contact: OpenModelica@ida.liu.se

Modelica\ :sup:`®` is a registered trademark of the Modelica
Association, https://www.Modelica.org

Mathematica\ :sup:`®` is a registered trademark of Wolfram Research Inc,
http://www.wolfram.com

This users guide provides documentation and examples on how to use the
OpenModelica system, both for the Modelica beginners and advanced users.

