| Copyright © 1998-|today| Open Source Modelica Consortium (OSMC)
| c/o Linköpings universitet, Department of Computer and Information Science
| SE-58183 Linköping, Sweden

.. image :: media/cc-by.*
  :alt: Creative Commons License
  :target: http://creativecommons.org/licenses/by/4.0/

This work is licensed under a `Creative Commons Attribution 4.0 International License <http://creativecommons.org/licenses/by/4.0/>`__.

This document is part of OpenModelica: https://www.openmodelica.org
Contact: OpenModelica@ida.liu.se

Modelica\ :sup:`®` is a registered trademark of the Modelica
Association, https://www.Modelica.org

Mathematica\ :sup:`®` is a registered trademark of Wolfram Research Inc,
http://www.wolfram.com

This users guide provides documentation and examples on how to use the
OpenModelica system, both for the Modelica beginners and advanced users.

