#!/bin/sh
RML="$1"
filerml="$2"
file=`basename $filerml .rml`
fileo="${file}.o"
fileh="${file}.h"
implfile="$2.impl"
temprml="${file}.tmp.rml"
temp=`basename $temprml .rml`
tempo="${temp}.o"
temph="${temp}.h"

cat ${filerml} ${implfile} > ${temprml}
if ( `${RML} -c ${temprml}` ) then
mv ${tempo} ${fileo}
mv ${temph} ${fileh}
rm ${temprml}
else
return 1
fi
