# Cut down from Modelica/Resources/BuildProjects/CMake/Modelica_platform.cmake,
# plus the WASI branch the MSL is missing.
function(get_modelica_platform_name var)
  if(CMAKE_SYSTEM_NAME STREQUAL "WASI")
    set(PLATFORM_PATH_SUFFIX "wasm32-wasip1")
  elseif(APPLE)
    if(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64")
      set(PLATFORM_PATH_SUFFIX "aarch64-darwin")
    else()
      set(PLATFORM_PATH_SUFFIX "darwin64")
    endif()
  elseif(UNIX)
    set(PLATFORM_PATH_SUFFIX "linux64")
  elseif(MSVC OR MINGW)
    set(PLATFORM_PATH_SUFFIX "win64")
  else()
    message(FATAL_ERROR "Unsupported compiler environment")
  endif()
  if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    string(REPLACE "64" "32" PLATFORM_PATH_SUFFIX "${PLATFORM_PATH_SUFFIX}")
  endif()

  message(STATUS "Building for Modelica platform ${PLATFORM_PATH_SUFFIX}")
  set(${var} ${PLATFORM_PATH_SUFFIX} PARENT_SCOPE)
endfunction()
