# As Modelica/Resources/BuildProjects/CMake/Modelica_utilities.cmake asks for it.
if(NOT DEFINED MODELICA_UTILITIES_INCLUDE_DIR OR MODELICA_UTILITIES_INCLUDE_DIR STREQUAL "")
  message(FATAL_ERROR "MODELICA_UTILITIES_INCLUDE_DIR is not set.")
endif()
file(TO_CMAKE_PATH ${MODELICA_UTILITIES_INCLUDE_DIR} MODELICA_UTILITIES_INCLUDE_DIR)
include_directories(${MODELICA_UTILITIES_INCLUDE_DIR})
