//! Compiles `src/shim.c`, and derives the ABI layout checks
//! (`tests/abi_layout.rs`) from `src/abi.rs`.
//!
//! Every `#[repr(C)] pub struct` in the mirror becomes a `sizeof` check plus one
//! `offsetof` per field, and every `FLAG_*` constant an index check, each paired
//! with the same expression in C. Generating them keeps the check list from
//! drifting away from the mirror it is checking.

use std::fmt::Write as _;
use std::path::PathBuf;

/// libOpenModelicaRuntimeC, which owns the state this runtime shares with the
/// generated code. Only an ELF `.so` may leave those to bind from the executable
/// at load, so `--no-undefined` holds it to what a DLL and a dylib require.
fn link_runtime_c() {
    println!("cargo:rerun-if-env-changed=OMC_RUNTIME_C_DIR");
    println!("cargo:rerun-if-env-changed=OMC_RUNTIME_C_LINK");
    // MSVC links the static archive *into* SimulationRuntimeC.dll, so absorb it
    // the same way. CMake names its dependencies, which an archive lacks.
    if let Ok(libs) = std::env::var("OMC_RUNTIME_C_LINK") {
        for lib in libs.split('|').filter(|s| !s.is_empty()) {
            println!("cargo:rustc-cdylib-link-arg={lib}");
        }
        return;
    }
    let Ok(dir) = std::env::var("OMC_RUNTIME_C_DIR") else { return };
    println!("cargo:rustc-link-search=native={dir}");
    println!("cargo:rustc-link-lib=dylib=OpenModelicaRuntimeC");
    if !matches!(std::env::var("CARGO_CFG_TARGET_OS").as_deref(), Ok("windows" | "macos" | "ios")) {
        println!("cargo:rustc-cdylib-link-arg=-Wl,--no-undefined");
    }
}

/// BLAS and LAPACK, which a dylib must resolve where an ELF `.so` leaves them to
/// the executable. macOS ships them in Accelerate, under the same Fortran names.
fn link_blas() {
    if !matches!(std::env::var("CARGO_CFG_TARGET_OS").as_deref(), Ok("macos" | "ios")) {
        return;
    }
    // Cross-compiling the frameworks live in the SDK, and only the compiler has
    // been told where that is (-iframework), not the linker.
    println!("cargo:rerun-if-env-changed=SDKROOT");
    if let Ok(sdk) = std::env::var("SDKROOT") {
        println!("cargo:rustc-cdylib-link-arg=-F{sdk}/System/Library/Frameworks");
    }
    println!("cargo:rustc-cdylib-link-arg=-framework");
    println!("cargo:rustc-cdylib-link-arg=Accelerate");
}

/// The variadic entry points src/shim.c defines.
const SHIM_ENTRY_POINTS: &[&str] = &[
    "omc_assert_simulation",
    "omc_assert_simulation_withEquationIndexes",
    "omc_assert_warning_simulation",
    "omc_assert_warning_simulation_withEquationIndexes",
    "omc_terminate_simulation",
];

/// A cdylib exports only the symbols Rust itself defines, so without this the
/// generated model does not link.
fn export_shim_entry_points() {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        // link.exe honours the objects' __declspec(dllexport) alongside its /DEF.
        Ok("windows") => {}
        Ok("macos" | "ios") => {
            let path = out.join("shim_exports.txt");
            let names: String = SHIM_ENTRY_POINTS.iter().map(|s| format!("_{s}\n")).collect();
            std::fs::write(&path, names).expect("write the export list");
            println!("cargo:rustc-cdylib-link-arg=-Wl,-exported_symbols_list,{}", path.display());
        }
        _ => {
            let path = out.join("shim_exports.map");
            let names: String = SHIM_ENTRY_POINTS.iter().map(|s| format!("  {s};\n")).collect();
            std::fs::write(&path, format!("{{\n global:\n{names}}};\n")).expect("write the map");
            println!("cargo:rustc-cdylib-link-arg=-Wl,--version-script={}", path.display());
        }
    }
}

/// Mirror types that are not a C struct of the same name, or whose fields the C
/// side does not have under those names.
const SKIP: &[&str] = &["rtclock_t", "threadData_t"];
/// `field in Rust` -> `field in C`, where the C name is a Rust keyword.
const RENAME: &[(&str, &str)] = &[("ty", "type")];
/// Mirrors of a plain C `struct` with no typedef, which C must name with the tag.
const C_TAG: &[&str] = &["OpenModelicaGeneratedFunctionCallbacks"];

fn main() {
    println!("cargo:rerun-if-changed=src/shim.c");
    cc::Build::new().file("src/shim.c").warnings(true).compile("omc_rust_runtime_shim");
    export_shim_entry_points();
    link_runtime_c();
    link_blas();
    println!("cargo:rerun-if-changed=src/abi.rs");
    println!("cargo:rerun-if-env-changed=OMC_SIMRT_INCLUDE_DIRS");
    let src = std::fs::read_to_string("src/abi.rs").expect("src/abi.rs");
    let mut out = String::from(
        "/// (C expression, the mirror's value). Generated by build.rs from src/abi.rs.\n\
         fn checks() -> Vec<(String, u64)> {\n  let mut v: Vec<(String, u64)> = Vec::new();\n",
    );
    let mut lines = src.lines().peekable();
    while let Some(line) = lines.next() {
        if line.trim() != "#[repr(C)]" {
            continue;
        }
        // Skip the derives between the attribute and the item.
        let mut head = lines.next().unwrap_or("");
        while head.trim_start().starts_with("#[") {
            head = lines.next().unwrap_or("");
        }
        let Some(name) = head.trim().strip_prefix("pub struct ").and_then(|s| s.split_whitespace().next())
        else {
            continue;
        };
        if !head.trim_end().ends_with('{') || SKIP.contains(&name) {
            continue;
        }
        let c_name = if C_TAG.contains(&name) { format!("struct {name}") } else { name.to_string() };
        let _ = writeln!(
            out,
            "  v.push((\"sizeof({c_name})\".into(), core::mem::size_of::<abi::{name}>() as u64));"
        );
        // Fields end at the closing brace; `pub <name>:` at one indent level.
        let mut depth = 1usize;
        for body in lines.by_ref() {
            depth += body.matches('{').count();
            depth -= body.matches('}').count();
            if depth == 0 {
                break;
            }
            let t = body.trim();
            let Some(field) = t.strip_prefix("pub ").and_then(|s| s.split(':').next()) else { continue };
            if !field.chars().all(|c| c.is_alphanumeric() || c == '_') || field.is_empty() {
                continue;
            }
            let c_field = RENAME.iter().find(|(r, _)| *r == field).map_or(field, |(_, c)| *c);
            let _ = writeln!(
                out,
                "  v.push((\"offsetof({c_name}, {c_field})\".into(), core::mem::offset_of!(abi::{name}, {field}) as u64));"
            );
        }
    }
    // The `enum _FLAG` indices `omc_flag`/`omc_flagValue` are addressed with, the
    // `errorStage` values `threadData->currentErrorStage` takes, and the solver
    // enumerations `simulationInfo` holds.
    for line in src.lines() {
        let t = line.trim();
        for (prefix, ty) in [
            ("pub const FLAG_", ": usize = "),
            ("pub const ERROR_", ": i32 = "),
            ("pub const LS_", ": c_int = "),
            ("pub const NLS_", ": c_int = "),
        ] {
            let Some(rest) = t.strip_prefix(prefix) else { continue };
            let Some((name, value)) = rest.split_once(ty) else { continue };
            let value = value.trim_end_matches(';');
            let c_name = &prefix["pub const ".len()..];
            let _ = writeln!(out, "  v.push((\"{c_name}{name}\".into(), {value}u64));");
        }
    }
    out.push_str("  v\n}\n");
    let path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("abi_layout_checks.rs");
    std::fs::write(&path, out).expect("write the layout checks");
}
