# Test 1
add_executable(test_boolean_vector_to_string
  01_test_boolean_vector_to_string.c
)
target_link_libraries(test_boolean_vector_to_string PRIVATE SimulationRuntimeC)
add_test(NAME test_boolean_vector_to_string COMMAND test_boolean_vector_to_string)

add_custom_target(ctestsuite-util-boolean_array DEPENDS
  test_boolean_vector_to_string
)
