#include "../omc_simulation_settings.h"
#include "../meta/meta_modelica.h"
static const MMC_DEFSTRINGLIT(OMC_STRINGLIT_0,0,"");
void* mmc_emptystring = MMC_REFSTRINGLIT(OMC_STRINGLIT_0);
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_01,1,"\x01");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_02,1,"\x02");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_03,1,"\x03");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_04,1,"\x04");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_05,1,"\x05");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_06,1,"\x06");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_07,1,"\x07");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_08,1,"\x08");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_09,1,"\x09");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0A,1,"\x0A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0B,1,"\x0B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0C,1,"\x0C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0D,1,"\x0D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0E,1,"\x0E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0F,1,"\x0F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_10,1,"\x10");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_11,1,"\x11");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_12,1,"\x12");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_13,1,"\x13");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_14,1,"\x14");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_15,1,"\x15");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_16,1,"\x16");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_17,1,"\x17");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_18,1,"\x18");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_19,1,"\x19");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1A,1,"\x1A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1B,1,"\x1B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1C,1,"\x1C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1D,1,"\x1D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1E,1,"\x1E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1F,1,"\x1F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_20,1,"\x20");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_21,1,"\x21");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_22,1,"\x22");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_23,1,"\x23");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_24,1,"\x24");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_25,1,"\x25");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_26,1,"\x26");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_27,1,"\x27");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_28,1,"\x28");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_29,1,"\x29");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2A,1,"\x2A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2B,1,"\x2B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2C,1,"\x2C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2D,1,"\x2D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2E,1,"\x2E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2F,1,"\x2F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_30,1,"\x30");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_31,1,"\x31");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_32,1,"\x32");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_33,1,"\x33");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_34,1,"\x34");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_35,1,"\x35");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_36,1,"\x36");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_37,1,"\x37");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_38,1,"\x38");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_39,1,"\x39");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3A,1,"\x3A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3B,1,"\x3B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3C,1,"\x3C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3D,1,"\x3D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3E,1,"\x3E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3F,1,"\x3F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_40,1,"\x40");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_41,1,"\x41");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_42,1,"\x42");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_43,1,"\x43");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_44,1,"\x44");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_45,1,"\x45");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_46,1,"\x46");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_47,1,"\x47");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_48,1,"\x48");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_49,1,"\x49");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4A,1,"\x4A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4B,1,"\x4B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4C,1,"\x4C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4D,1,"\x4D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4E,1,"\x4E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4F,1,"\x4F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_50,1,"\x50");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_51,1,"\x51");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_52,1,"\x52");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_53,1,"\x53");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_54,1,"\x54");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_55,1,"\x55");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_56,1,"\x56");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_57,1,"\x57");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_58,1,"\x58");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_59,1,"\x59");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5A,1,"\x5A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5B,1,"\x5B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5C,1,"\x5C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5D,1,"\x5D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5E,1,"\x5E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5F,1,"\x5F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_60,1,"\x60");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_61,1,"\x61");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_62,1,"\x62");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_63,1,"\x63");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_64,1,"\x64");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_65,1,"\x65");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_66,1,"\x66");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_67,1,"\x67");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_68,1,"\x68");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_69,1,"\x69");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6A,1,"\x6A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6B,1,"\x6B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6C,1,"\x6C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6D,1,"\x6D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6E,1,"\x6E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6F,1,"\x6F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_70,1,"\x70");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_71,1,"\x71");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_72,1,"\x72");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_73,1,"\x73");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_74,1,"\x74");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_75,1,"\x75");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_76,1,"\x76");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_77,1,"\x77");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_78,1,"\x78");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_79,1,"\x79");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7A,1,"\x7A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7B,1,"\x7B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7C,1,"\x7C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7D,1,"\x7D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7E,1,"\x7E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7F,1,"\x7F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_80,1,"\x80");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_81,1,"\x81");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_82,1,"\x82");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_83,1,"\x83");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_84,1,"\x84");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_85,1,"\x85");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_86,1,"\x86");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_87,1,"\x87");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_88,1,"\x88");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_89,1,"\x89");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8A,1,"\x8A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8B,1,"\x8B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8C,1,"\x8C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8D,1,"\x8D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8E,1,"\x8E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8F,1,"\x8F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_90,1,"\x90");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_91,1,"\x91");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_92,1,"\x92");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_93,1,"\x93");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_94,1,"\x94");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_95,1,"\x95");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_96,1,"\x96");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_97,1,"\x97");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_98,1,"\x98");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_99,1,"\x99");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9A,1,"\x9A");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9B,1,"\x9B");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9C,1,"\x9C");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9D,1,"\x9D");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9E,1,"\x9E");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9F,1,"\x9F");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A0,1,"\xA0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A1,1,"\xA1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A2,1,"\xA2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A3,1,"\xA3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A4,1,"\xA4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A5,1,"\xA5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A6,1,"\xA6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A7,1,"\xA7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A8,1,"\xA8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A9,1,"\xA9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AA,1,"\xAA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AB,1,"\xAB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AC,1,"\xAC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AD,1,"\xAD");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AE,1,"\xAE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AF,1,"\xAF");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B0,1,"\xB0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B1,1,"\xB1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B2,1,"\xB2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B3,1,"\xB3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B4,1,"\xB4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B5,1,"\xB5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B6,1,"\xB6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B7,1,"\xB7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B8,1,"\xB8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B9,1,"\xB9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BA,1,"\xBA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BB,1,"\xBB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BC,1,"\xBC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BD,1,"\xBD");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BE,1,"\xBE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BF,1,"\xBF");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C0,1,"\xC0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C1,1,"\xC1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C2,1,"\xC2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C3,1,"\xC3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C4,1,"\xC4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C5,1,"\xC5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C6,1,"\xC6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C7,1,"\xC7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C8,1,"\xC8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C9,1,"\xC9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CA,1,"\xCA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CB,1,"\xCB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CC,1,"\xCC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CD,1,"\xCD");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CE,1,"\xCE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CF,1,"\xCF");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D0,1,"\xD0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D1,1,"\xD1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D2,1,"\xD2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D3,1,"\xD3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D4,1,"\xD4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D5,1,"\xD5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D6,1,"\xD6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D7,1,"\xD7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D8,1,"\xD8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D9,1,"\xD9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DA,1,"\xDA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DB,1,"\xDB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DC,1,"\xDC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DD,1,"\xDD");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DE,1,"\xDE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DF,1,"\xDF");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E0,1,"\xE0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E1,1,"\xE1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E2,1,"\xE2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E3,1,"\xE3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E4,1,"\xE4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E5,1,"\xE5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E6,1,"\xE6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E7,1,"\xE7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E8,1,"\xE8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E9,1,"\xE9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EA,1,"\xEA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EB,1,"\xEB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EC,1,"\xEC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_ED,1,"\xED");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EE,1,"\xEE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EF,1,"\xEF");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F0,1,"\xF0");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F1,1,"\xF1");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F2,1,"\xF2");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F3,1,"\xF3");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F4,1,"\xF4");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F5,1,"\xF5");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F6,1,"\xF6");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F7,1,"\xF7");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F8,1,"\xF8");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F9,1,"\xF9");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FA,1,"\xFA");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FB,1,"\xFB");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FC,1,"\xFC");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FD,1,"\xFD");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FE,1,"\xFE");
static MMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FF,1,"\xFF");
void* mmc_strings_len1[256] = {
NULL,
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_01),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_02),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_03),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_04),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_05),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_06),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_07),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_08),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_09),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_0F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_10),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_11),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_12),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_13),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_14),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_15),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_16),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_17),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_18),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_19),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_1F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_20),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_21),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_22),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_23),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_24),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_25),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_26),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_27),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_28),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_29),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_2F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_30),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_31),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_32),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_33),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_34),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_35),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_36),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_37),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_38),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_39),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_3F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_40),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_41),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_42),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_43),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_44),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_45),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_46),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_47),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_48),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_49),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_4F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_50),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_51),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_52),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_53),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_54),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_55),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_56),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_57),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_58),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_59),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_5F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_60),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_61),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_62),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_63),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_64),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_65),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_66),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_67),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_68),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_69),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_6F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_70),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_71),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_72),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_73),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_74),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_75),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_76),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_77),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_78),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_79),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_7F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_80),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_81),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_82),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_83),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_84),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_85),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_86),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_87),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_88),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_89),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_8F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_90),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_91),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_92),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_93),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_94),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_95),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_96),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_97),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_98),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_99),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9A),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9B),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9C),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9D),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9E),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_9F),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_A9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AD),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_AF),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_B9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BD),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_BF),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_C9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CD),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_CF),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_D9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DD),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_DF),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_E9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_EA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_EB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_EC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_ED),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_EE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_EF),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F1),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F2),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F3),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F4),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F5),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F6),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F7),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F8),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_F9),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FA),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FB),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FC),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FD),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FE),
MMC_REFSTRINGLIT(OMC_STRINGLIT_1_FF),
};

static MMC_DEFSTRINGLIT(OMC_STRINGLIT_UNINITIALIZED,23,"$#*OMC_UNINITIALIZED*#$");
void* mmc_string_uninitialized = MMC_REFSTRINGLIT(OMC_STRINGLIT_UNINITIALIZED);

static const MMC_DEFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_0,5,"false");
static const MMC_DEFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_1,4,"true");
void* mmc_strings_boolString[2] = {
MMC_REFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_0),
MMC_REFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_1)
};
