/*
 * This file belongs to the OpenModelica Run-Time System
 *
 * Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC), c/o Linköpings
 * universitet, Department of Computer and Information Science, SE-58183 Linköping, Sweden. All rights
 * reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF THE BSD NEW LICENSE OR THE
 * AGPL VERSION 3 LICENSE OR THE OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8. ANY
 * USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES RECIPIENT'S
 * ACCEPTANCE OF THE BSD NEW LICENSE OR THE OSMC PUBLIC LICENSE OR THE AGPL
 * VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
 *
 * The OpenModelica software and the OSMC (Open Source Modelica Consortium) Public License
 * (OSMC-PL) are obtained from OSMC, either from the above address, from the URLs:
 * http://www.openmodelica.org or https://github.com/OpenModelica/ or
 * http://www.ida.liu.se/projects/OpenModelica, and in the OpenModelica distribution. GNU
 * AGPL version 3 is obtained from: https://www.gnu.org/licenses/licenses.html#GPL. The BSD NEW
 * License is obtained from: http://www.opensource.org/licenses/BSD-3-Clause.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, EXCEPT AS EXPRESSLY
 * SET FORTH IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE CONDITIONS OF
 * OSMC-PL.
 *
 */

#include "omc_string.h"
#include "modelica_string_lit.h"
static const OMC_DEFSTRINGLIT(OMC_STRINGLIT_0,0,"");
modelica_string omc_string_empty = OMC_REFSTRINGLIT(OMC_STRINGLIT_0);
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_01,1,"\x01");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_02,1,"\x02");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_03,1,"\x03");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_04,1,"\x04");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_05,1,"\x05");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_06,1,"\x06");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_07,1,"\x07");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_08,1,"\x08");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_09,1,"\x09");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0A,1,"\x0A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0B,1,"\x0B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0C,1,"\x0C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0D,1,"\x0D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0E,1,"\x0E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_0F,1,"\x0F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_10,1,"\x10");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_11,1,"\x11");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_12,1,"\x12");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_13,1,"\x13");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_14,1,"\x14");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_15,1,"\x15");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_16,1,"\x16");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_17,1,"\x17");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_18,1,"\x18");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_19,1,"\x19");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1A,1,"\x1A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1B,1,"\x1B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1C,1,"\x1C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1D,1,"\x1D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1E,1,"\x1E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_1F,1,"\x1F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_20,1,"\x20");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_21,1,"\x21");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_22,1,"\x22");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_23,1,"\x23");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_24,1,"\x24");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_25,1,"\x25");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_26,1,"\x26");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_27,1,"\x27");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_28,1,"\x28");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_29,1,"\x29");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2A,1,"\x2A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2B,1,"\x2B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2C,1,"\x2C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2D,1,"\x2D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2E,1,"\x2E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_2F,1,"\x2F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_30,1,"\x30");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_31,1,"\x31");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_32,1,"\x32");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_33,1,"\x33");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_34,1,"\x34");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_35,1,"\x35");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_36,1,"\x36");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_37,1,"\x37");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_38,1,"\x38");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_39,1,"\x39");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3A,1,"\x3A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3B,1,"\x3B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3C,1,"\x3C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3D,1,"\x3D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3E,1,"\x3E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_3F,1,"\x3F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_40,1,"\x40");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_41,1,"\x41");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_42,1,"\x42");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_43,1,"\x43");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_44,1,"\x44");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_45,1,"\x45");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_46,1,"\x46");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_47,1,"\x47");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_48,1,"\x48");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_49,1,"\x49");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4A,1,"\x4A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4B,1,"\x4B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4C,1,"\x4C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4D,1,"\x4D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4E,1,"\x4E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_4F,1,"\x4F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_50,1,"\x50");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_51,1,"\x51");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_52,1,"\x52");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_53,1,"\x53");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_54,1,"\x54");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_55,1,"\x55");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_56,1,"\x56");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_57,1,"\x57");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_58,1,"\x58");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_59,1,"\x59");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5A,1,"\x5A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5B,1,"\x5B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5C,1,"\x5C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5D,1,"\x5D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5E,1,"\x5E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_5F,1,"\x5F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_60,1,"\x60");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_61,1,"\x61");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_62,1,"\x62");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_63,1,"\x63");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_64,1,"\x64");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_65,1,"\x65");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_66,1,"\x66");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_67,1,"\x67");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_68,1,"\x68");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_69,1,"\x69");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6A,1,"\x6A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6B,1,"\x6B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6C,1,"\x6C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6D,1,"\x6D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6E,1,"\x6E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_6F,1,"\x6F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_70,1,"\x70");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_71,1,"\x71");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_72,1,"\x72");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_73,1,"\x73");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_74,1,"\x74");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_75,1,"\x75");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_76,1,"\x76");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_77,1,"\x77");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_78,1,"\x78");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_79,1,"\x79");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7A,1,"\x7A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7B,1,"\x7B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7C,1,"\x7C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7D,1,"\x7D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7E,1,"\x7E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_7F,1,"\x7F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_80,1,"\x80");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_81,1,"\x81");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_82,1,"\x82");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_83,1,"\x83");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_84,1,"\x84");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_85,1,"\x85");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_86,1,"\x86");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_87,1,"\x87");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_88,1,"\x88");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_89,1,"\x89");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8A,1,"\x8A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8B,1,"\x8B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8C,1,"\x8C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8D,1,"\x8D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8E,1,"\x8E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_8F,1,"\x8F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_90,1,"\x90");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_91,1,"\x91");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_92,1,"\x92");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_93,1,"\x93");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_94,1,"\x94");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_95,1,"\x95");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_96,1,"\x96");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_97,1,"\x97");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_98,1,"\x98");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_99,1,"\x99");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9A,1,"\x9A");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9B,1,"\x9B");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9C,1,"\x9C");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9D,1,"\x9D");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9E,1,"\x9E");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_9F,1,"\x9F");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A0,1,"\xA0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A1,1,"\xA1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A2,1,"\xA2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A3,1,"\xA3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A4,1,"\xA4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A5,1,"\xA5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A6,1,"\xA6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A7,1,"\xA7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A8,1,"\xA8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_A9,1,"\xA9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AA,1,"\xAA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AB,1,"\xAB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AC,1,"\xAC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AD,1,"\xAD");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AE,1,"\xAE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_AF,1,"\xAF");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B0,1,"\xB0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B1,1,"\xB1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B2,1,"\xB2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B3,1,"\xB3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B4,1,"\xB4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B5,1,"\xB5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B6,1,"\xB6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B7,1,"\xB7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B8,1,"\xB8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_B9,1,"\xB9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BA,1,"\xBA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BB,1,"\xBB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BC,1,"\xBC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BD,1,"\xBD");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BE,1,"\xBE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_BF,1,"\xBF");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C0,1,"\xC0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C1,1,"\xC1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C2,1,"\xC2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C3,1,"\xC3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C4,1,"\xC4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C5,1,"\xC5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C6,1,"\xC6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C7,1,"\xC7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C8,1,"\xC8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_C9,1,"\xC9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CA,1,"\xCA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CB,1,"\xCB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CC,1,"\xCC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CD,1,"\xCD");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CE,1,"\xCE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_CF,1,"\xCF");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D0,1,"\xD0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D1,1,"\xD1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D2,1,"\xD2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D3,1,"\xD3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D4,1,"\xD4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D5,1,"\xD5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D6,1,"\xD6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D7,1,"\xD7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D8,1,"\xD8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_D9,1,"\xD9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DA,1,"\xDA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DB,1,"\xDB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DC,1,"\xDC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DD,1,"\xDD");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DE,1,"\xDE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_DF,1,"\xDF");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E0,1,"\xE0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E1,1,"\xE1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E2,1,"\xE2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E3,1,"\xE3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E4,1,"\xE4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E5,1,"\xE5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E6,1,"\xE6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E7,1,"\xE7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E8,1,"\xE8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_E9,1,"\xE9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EA,1,"\xEA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EB,1,"\xEB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EC,1,"\xEC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_ED,1,"\xED");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EE,1,"\xEE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_EF,1,"\xEF");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F0,1,"\xF0");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F1,1,"\xF1");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F2,1,"\xF2");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F3,1,"\xF3");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F4,1,"\xF4");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F5,1,"\xF5");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F6,1,"\xF6");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F7,1,"\xF7");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F8,1,"\xF8");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_F9,1,"\xF9");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FA,1,"\xFA");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FB,1,"\xFB");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FC,1,"\xFC");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FD,1,"\xFD");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FE,1,"\xFE");
static OMC_DEFSTRINGLIT(OMC_STRINGLIT_1_FF,1,"\xFF");
modelica_string omc_strings_len1[256] = {
NULL,
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_01),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_02),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_03),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_04),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_05),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_06),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_07),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_08),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_09),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_0F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_10),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_11),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_12),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_13),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_14),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_15),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_16),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_17),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_18),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_19),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_1F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_20),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_21),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_22),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_23),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_24),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_25),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_26),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_27),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_28),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_29),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_2F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_30),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_31),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_32),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_33),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_34),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_35),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_36),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_37),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_38),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_39),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_3F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_40),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_41),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_42),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_43),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_44),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_45),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_46),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_47),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_48),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_49),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_4F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_50),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_51),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_52),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_53),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_54),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_55),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_56),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_57),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_58),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_59),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_5F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_60),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_61),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_62),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_63),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_64),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_65),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_66),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_67),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_68),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_69),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_6F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_70),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_71),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_72),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_73),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_74),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_75),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_76),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_77),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_78),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_79),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_7F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_80),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_81),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_82),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_83),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_84),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_85),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_86),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_87),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_88),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_89),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_8F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_90),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_91),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_92),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_93),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_94),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_95),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_96),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_97),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_98),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_99),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9A),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9B),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9C),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9D),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9E),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_9F),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_A9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AD),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_AF),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_B9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BD),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_BF),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_C9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CD),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_CF),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_D9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DD),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_DF),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_E9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_EA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_EB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_EC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_ED),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_EE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_EF),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F1),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F2),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F3),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F4),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F5),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F6),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F7),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F8),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_F9),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FA),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FB),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FC),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FD),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FE),
OMC_REFSTRINGLIT(OMC_STRINGLIT_1_FF),
};

static OMC_DEFSTRINGLIT(OMC_STRINGLIT_UNINITIALIZED,23,"$#*OMC_UNINITIALIZED*#$");
modelica_string omc_string_uninitialized = OMC_REFSTRINGLIT(OMC_STRINGLIT_UNINITIALIZED);

static const OMC_DEFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_0,5,"false");
static const OMC_DEFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_1,4,"true");
modelica_string omc_strings_boolString[2] = {
OMC_REFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_0),
OMC_REFSTRINGLIT(OMC_STRINGLIT_BOOLSTRING_1)
};
