TEST = ../../../rtest -v

TESTFILES = \
Modelica.Blocks.Examples.BooleanNetwork1.mos \
Modelica.Blocks.Examples.BusUsage.mos \
Modelica.Blocks.Examples.Filter.mos \
Modelica.Blocks.Examples.FilterWithDifferentiation.mos \
Modelica.Blocks.Examples.FilterWithRiseTime.mos \
Modelica.Blocks.Examples.IntegerNetwork1.mos \
Modelica.Blocks.Examples.Interaction1.mos \
Modelica.Blocks.Examples.InverseModel.mos \
Modelica.Blocks.Examples.LogicalNetwork1.mos \
Modelica.Blocks.Examples.PID_Controller.mos \
Modelica.Blocks.Examples.RealNetwork1.mos \
Modelica.Blocks.Examples.ShowLogicalSources.mos \
Modelica.ComplexBlocks.Examples.TestConversionBlock.mos \
Modelica.Electrical.Analog.Examples.AD_DA_conversion.mos \
Modelica.Electrical.Analog.Examples.AmplifierWithOpAmpDetailed.mos \
Modelica.Electrical.Analog.Examples.CauerLowPassAnalog.mos \
Modelica.Electrical.Analog.Examples.CauerLowPassOPV.mos \
Modelica.Electrical.Analog.Examples.CauerLowPassSC.mos \
Modelica.Electrical.Analog.Examples.CharacteristicIdealDiodes.mos \
Modelica.Electrical.Analog.Examples.CharacteristicThyristors.mos \
Modelica.Electrical.Analog.Examples.ChuaCircuit.mos \
Modelica.Electrical.Analog.Examples.CompareTransformers.mos \
Modelica.Electrical.Analog.Examples.ControlledSwitchWithArc.mos \
Modelica.Electrical.Analog.Examples.DifferenceAmplifier.mos \
Modelica.Electrical.Analog.Examples.HeatingMOSInverter.mos \
Modelica.Electrical.Analog.Examples.HeatingNPN_OrGate.mos \
Modelica.Electrical.Analog.Examples.HeatingRectifier.mos \
Modelica.Electrical.Analog.Examples.HeatingResistor.mos \
Modelica.Electrical.Analog.Examples.IdealTriacCircuit.mos \
Modelica.Electrical.Analog.Examples.NandGate.mos \
Modelica.Electrical.Analog.Examples.OvervoltageProtection.mos \
Modelica.Electrical.Analog.Examples.Rectifier.mos \
Modelica.Electrical.Analog.Examples.ShowSaturatingInductor.mos \
Modelica.Electrical.Analog.Examples.ShowVariableResistor.mos \
Modelica.Electrical.Analog.Examples.SimpleTriacCircuit.mos \
Modelica.Electrical.Analog.Examples.SwitchWithArc.mos \
Modelica.Electrical.Analog.Examples.ThyristorBehaviourTest.mos \
Modelica.Electrical.Digital.Examples.Adder4.mos \
Modelica.Electrical.Digital.Examples.BUF3S.mos \
Modelica.Electrical.Digital.Examples.Counter.mos \
Modelica.Electrical.Digital.Examples.Counter3.mos \
Modelica.Electrical.Digital.Examples.DFFREG.mos \
Modelica.Electrical.Digital.Examples.DFFREGL.mos \
Modelica.Electrical.Digital.Examples.DFFREGSRH.mos \
Modelica.Electrical.Digital.Examples.DFFREGSRL.mos \
Modelica.Electrical.Digital.Examples.DLATREG.mos \
Modelica.Electrical.Digital.Examples.DLATREGL.mos \
Modelica.Electrical.Digital.Examples.DLATREGSRH.mos \
Modelica.Electrical.Digital.Examples.DLATREGSRL.mos \
Modelica.Electrical.Digital.Examples.FlipFlop.mos \
Modelica.Electrical.Digital.Examples.FullAdder.mos \
Modelica.Electrical.Digital.Examples.HalfAdder.mos \
Modelica.Electrical.Digital.Examples.INV3S.mos \
Modelica.Electrical.Digital.Examples.Multiplexer.mos \
Modelica.Electrical.Digital.Examples.MUX2x1.mos \
Modelica.Electrical.Digital.Examples.NRXFER.mos \
Modelica.Electrical.Digital.Examples.NXFER.mos \
Modelica.Electrical.Digital.Examples.RAM.mos \
Modelica.Electrical.Digital.Examples.VectorDelay.mos \
Modelica.Electrical.Digital.Examples.WiredX.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_DOL.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_Initialize.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_Inverter.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_Steinmetz.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_Transformer.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_withLosses.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMC_YD.mos \
Modelica.Electrical.Machines.Examples.AsynchronousInductionMachines.AIMS_Start.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCEE_Start.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Cooling.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCPM_QuasiStationary.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Start.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Temperature.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCPM_withLosses.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCSE_SinglePhase.mos \
Modelica.Electrical.Machines.Examples.DCMachines.DCSE_Start.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMEE_Generator.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMEE_LoadDump.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMEE_Rectifier.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMPM_CurrentSource.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMPM_Inverter.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMPM_VoltageSource.mos \
Modelica.Electrical.Machines.Examples.SynchronousInductionMachines.SMR_Inverter.mos \
Modelica.Electrical.Machines.Examples.Transformers.AIMC_Transformer.mos \
Modelica.Electrical.Machines.Examples.Transformers.AsymmetricalLoad.mos \
Modelica.Electrical.Machines.Examples.Transformers.Rectifier12pulse.mos \
Modelica.Electrical.Machines.Examples.Transformers.Rectifier6pulse.mos \
Modelica.Electrical.Machines.Examples.Transformers.TransformerTestbench.mos \
Modelica.Electrical.MultiPhase.Examples.Rectifier.mos \
Modelica.Electrical.MultiPhase.Examples.TestSensors.mos \
Modelica.Electrical.MultiPhase.Examples.TransformerYD.mos \
Modelica.Electrical.MultiPhase.Examples.TransformerYY.mos \
Modelica.Electrical.QuasiStationary.Machines.Examples.TransformerTestbench.mos \
Modelica.Electrical.QuasiStationary.MultiPhase.Examples.BalancingDelta.mos \
Modelica.Electrical.QuasiStationary.MultiPhase.Examples.BalancingStar.mos \
Modelica.Electrical.QuasiStationary.SinglePhase.Examples.ParallelResonance.mos \
Modelica.Electrical.QuasiStationary.SinglePhase.Examples.Rectifier.mos \
Modelica.Electrical.QuasiStationary.SinglePhase.Examples.SeriesResonance.mos \
Modelica.Electrical.Spice3.Examples.CascodeCircuit.mos \
Modelica.Electrical.Spice3.Examples.CoupledInductors.mos \
Modelica.Electrical.Spice3.Examples.FourInverters.mos \
Modelica.Electrical.Spice3.Examples.Graetz.mos \
Modelica.Electrical.Spice3.Examples.Inverter.mos \
Modelica.Electrical.Spice3.Examples.InvertersApartRecord.mos \
Modelica.Electrical.Spice3.Examples.InvertersExtendedModel.mos \
Modelica.Electrical.Spice3.Examples.Nand.mos \
Modelica.Electrical.Spice3.Examples.Nor.mos \
Modelica.Electrical.Spice3.Examples.Oscillator.mos \
Modelica.Electrical.Spice3.Examples.Spice3BenchmarkDifferentialPair.mos \
Modelica.Electrical.Spice3.Examples.Spice3BenchmarkFourBitBinaryAdder.mos \
Modelica.Electrical.Spice3.Examples.Spice3BenchmarkMosfetCharacterization.mos \
Modelica.Electrical.Spice3.Examples.Spice3BenchmarkRtlInverter.mos \
Modelica.Fluid.Examples.AST_BatchPlant.BatchPlant_StandardWater.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.OneTank.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.TanksWithEmptyingPipe1.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.TanksWithEmptyingPipe2.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.TankWithEmptyingPipe1.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.TankWithEmptyingPipe2.mos \
Modelica.Fluid.Examples.AST_BatchPlant.Test.TwoTanks.mos \
Modelica.Fluid.Examples.BranchingDynamicPipes.mos \
Modelica.Fluid.Examples.ControlledTankSystem.ControlledTanks.mos \
Modelica.Fluid.Examples.DrumBoiler.DrumBoiler.mos \
Modelica.Fluid.Examples.Explanatory.MeasuringTemperature.mos \
Modelica.Fluid.Examples.Explanatory.MomentumBalanceFittings.mos \
Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation.mos \
Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation-addDerAlias.mos \
Modelica.Fluid.Examples.HeatingSystem.mos \
Modelica.Fluid.Examples.IncompressibleFluidNetwork.mos \
Modelica.Fluid.Examples.InverseParameterization.mos \
Modelica.Fluid.Examples.Tanks.EmptyTanks.mos \
Modelica.Fluid.Examples.Tanks.TanksWithOverflow.mos \
Modelica.Fluid.Examples.Tanks.ThreeTanks.mos \
Modelica.Fluid.Examples.TraceSubstances.RoomCO2.mos \
Modelica.Fluid.Examples.TraceSubstances.RoomCO2WithControls.mos \
Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.ArmatureStroke.mos \
Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.ForceCurrentBehaviour.mos \
Modelica.Magnetic.FluxTubes.Examples.MovingCoilActuator.ForceStrokeBehaviour.mos \
Modelica.Magnetic.FluxTubes.Examples.SaturatedInductor.mos \
Modelica.Magnetic.FluxTubes.Examples.SolenoidActuator.ComparisonPullInStroke.mos \
Modelica.Magnetic.FluxTubes.Examples.SolenoidActuator.ComparisonQuasiStationary.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_DOL.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMC_DOL_MultiPhase.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMS_Start.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.AIMS_Start_MultiPhase.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMEE_Generator.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMPM_Inverter.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMPM_Inverter_MultiPhase.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMR_Inverter.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMR_Inverter_MultiPhase.mos \
Modelica.Magnetic.FundamentalWave.Examples.Components.EddyCurrentLosses.mos \
Modelica.Magnetic.FundamentalWave.Examples.Components.MultiPhaseInductance.mos \
Modelica.Magnetic.FundamentalWave.Examples.Components.SinglePhaseInductance.mos \
Modelica.Math.Nonlinear.Examples.quadratureLobatto3.mos \
Modelica.Mechanics.MultiBody.Examples.Constraints.RevoluteConstraint.mos \
Modelica.Mechanics.MultiBody.Examples.Constraints.PrismaticConstraint.mos \
Modelica.Mechanics.MultiBody.Examples.Constraints.SphericalConstraint.mos \
Modelica.Mechanics.MultiBody.Examples.Constraints.UniversalConstraint.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.DoublePendulum.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.DoublePendulumInitTip.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.ForceAndTorque.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.FreeBody.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.HeatLosses.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.InitSpringConstant.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.LineForceWithTwoMasses.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.PendulumWithSpringDamper.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.PointGravity.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.PointGravityWithPointMasses.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.PointGravityWithPointMasses2.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheel.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetDriving.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetPulling.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.SpringDamperSystem.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.SpringMassSystem.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.SpringWithMass.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.ThreeSprings.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Engine1a.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Engine1b.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Engine1b_analytic.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.EngineV6.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.EngineV6_analytic.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Fourbar1.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Fourbar2.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.Fourbar_analytic.mos \
Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.mos \
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.ActuatedDrive.mos \
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.GearConstraint.mos \
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.GyroscopicEffects.mos \
Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.MovingActuatedDrive.mos \
Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot.mos \
Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.oneAxis.mos \
Modelica.Mechanics.Rotational.Examples.Backlash.mos \
Modelica.Mechanics.Rotational.Examples.CoupledClutches.mos \
Modelica.Mechanics.Rotational.Examples.ElasticBearing.mos \
Modelica.Mechanics.Rotational.Examples.First.mos \
Modelica.Mechanics.Rotational.Examples.FirstGrounded.mos \
Modelica.Mechanics.Rotational.Examples.Friction.mos \
Modelica.Mechanics.Rotational.Examples.HeatLosses.mos \
Modelica.Mechanics.Rotational.Examples.LossyGearDemo1.mos \
Modelica.Mechanics.Rotational.Examples.LossyGearDemo2.mos \
Modelica.Mechanics.Rotational.Examples.LossyGearDemo3.mos \
Modelica.Mechanics.Rotational.Examples.RollingWheel.mos \
Modelica.Mechanics.Rotational.Examples.SimpleGearShift.mos \
Modelica.Mechanics.Translational.Examples.Accelerate.mos \
Modelica.Mechanics.Translational.Examples.Brake.mos \
Modelica.Mechanics.Translational.Examples.Damper.mos \
Modelica.Mechanics.Translational.Examples.ElastoGap.mos \
Modelica.Mechanics.Translational.Examples.Friction.mos \
Modelica.Mechanics.Translational.Examples.HeatLosses.mos \
Modelica.Mechanics.Translational.Examples.InitialConditions.mos \
Modelica.Mechanics.Translational.Examples.Oscillator.mos \
Modelica.Mechanics.Translational.Examples.PreLoad.mos \
Modelica.Mechanics.Translational.Examples.Sensors.mos \
Modelica.Mechanics.Translational.Examples.SignConvention.mos \
Modelica.Mechanics.Translational.Examples.WhyArrows.mos \
Modelica.Media.Examples.IdealGasH2O.mos \
Modelica.Media.Examples.MixtureGases.mos \
Modelica.Media.Examples.MoistAir.mos \
Modelica.Media.Examples.ReferenceAir.DryAir1.mos \
Modelica.Media.Examples.ReferenceAir.DryAir2.mos \
Modelica.Media.Examples.ReferenceAir.Inverse_sh_T.mos \
Modelica.Media.Examples.ReferenceAir.Inverse_sh_TX.mos \
Modelica.Media.Examples.ReferenceAir.MoistAir.mos \
Modelica.Media.Examples.ReferenceAir.MoistAir1.mos \
Modelica.Media.Examples.ReferenceAir.MoistAir2.mos \
Modelica.Media.Examples.SimpleLiquidWater.mos \
Modelica.Media.Examples.SolveOneNonlinearEquation.InverseIncompressible_sh_T.mos \
Modelica.Media.Examples.SolveOneNonlinearEquation.Inverse_sh_T.mos \
Modelica.Media.Examples.SolveOneNonlinearEquation.Inverse_sh_TX.mos \
Modelica.Media.Examples.TestOnly.FlueGas.mos \
Modelica.Media.Examples.TestOnly.IdealGasN2.mos \
Modelica.Media.Examples.TestOnly.IdealGasN2Mix.mos \
Modelica.Media.Examples.TestOnly.MixIdealGasAir.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Air.DryAirNasa.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Air.MoistAir.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Air.SimpleAir.mos \
Modelica.Media.Examples.Tests.MediaTestModels.IdealGases.Air.mos \
Modelica.Media.Examples.Tests.MediaTestModels.IdealGases.Nitrogen.mos \
Modelica.Media.Examples.Tests.MediaTestModels.IdealGases.SimpleNaturalGas.mos \
Modelica.Media.Examples.Tests.MediaTestModels.IdealGases.SimpleNaturalGasFixedComposition.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Incompressible.Essotherm650.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Incompressible.Glycol47.mos \
Modelica.Media.Examples.Tests.MediaTestModels.LinearFluid.LinearColdWater.mos \
Modelica.Media.Examples.Tests.MediaTestModels.LinearFluid.LinearWater_pT.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Water.ConstantPropertyLiquidWater.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Water.IdealSteam.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Water.WaterIF97OnePhase_ph.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Water.WaterIF97_ph.mos \
Modelica.Media.Examples.Tests.MediaTestModels.Water.WaterIF97_pT.mos \
Modelica.Media.Examples.TwoPhaseWater.TestTwoPhaseStates.mos \
Modelica.Media.Examples.WaterIF97.mos \
Modelica.Media.Incompressible.Examples.TestGlycol.mos \
Modelica.StateGraph.Examples.ControlledTanks.mos \
Modelica.StateGraph.Examples.ExecutionPaths.mos \
Modelica.StateGraph.Examples.FirstExample.mos \
Modelica.StateGraph.Examples.FirstExample_Variant2.mos \
Modelica.StateGraph.Examples.FirstExample_Variant3.mos \
Modelica.StateGraph.Examples.ShowCompositeStep.mos \
Modelica.StateGraph.Examples.ShowExceptions.mos \
Modelica.Thermal.FluidHeatFlow.Examples.IndirectCooling.mos \
Modelica.Thermal.FluidHeatFlow.Examples.OneMass.mos \
Modelica.Thermal.FluidHeatFlow.Examples.ParallelCooling.mos \
Modelica.Thermal.FluidHeatFlow.Examples.ParallelPumpDropOut.mos \
Modelica.Thermal.FluidHeatFlow.Examples.PumpAndValve.mos \
Modelica.Thermal.FluidHeatFlow.Examples.PumpDropOut.mos \
Modelica.Thermal.FluidHeatFlow.Examples.SimpleCooling.mos \
Modelica.Thermal.FluidHeatFlow.Examples.TwoMass.mos \
Modelica.Thermal.HeatTransfer.Examples.ControlledTemperature.mos \
Modelica.Thermal.HeatTransfer.Examples.Motor.mos \
Modelica.Thermal.HeatTransfer.Examples.TwoMasses.mos \
Modelica.Utilities.Examples.readRealParameterModel.mos \
Modelica.Mechanics.MultiBody.Examples.Elementary.UserDefinedGravityField.mos \
Modelica.Media.Examples.SolveOneNonlinearEquation.Inverse_sine.mos \
Modelica.Media.Examples.R134a.R134a1.mos \
Modelica.Media.Examples.R134a.R134a2.mos \
Modelica.Fluid.Examples.PumpingSystem.mos \
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMEE_Generator_MultiPhase.mos \

# Run make failingtest
FAILINGTESTFILES = \

# Dependency files that are not .mo .mos or Makefile
# Add them here or they will be cleaned.
DEPENDENCIES = \
*.mo \
*.mos \
Makefile \
ReferenceFiles \
simulateAll.sh \
simulateAll.cmd \
sortResults.py

CLEAN = `ls | grep -w -v -f deps.tmp`

.PHONY : test clean getdeps failingtest


test:
	@echo
	@echo Running tests...
	@echo
	@echo OPENMODELICAHOME=" $(OPENMODELICAHOME) "
	@$(TEST) $(TESTFILES)
	
# Cleans all files that are not listed as dependencies 
clean :
	@echo $(DEPENDENCIES) | sed 's/ /\\|/g' > deps.tmp
	@rm -f *.mos.txt
	@rm -rf $(CLEAN)

# Run this if you want to list out the files (dependencies).
# do it after cleaning and updating the folder
# then you can get a list of file names (which must be dependencies
# since you got them from repository + your own new files)
# then add them to the DEPENDENCIES. You can find the 
# list in deps.txt
getdeps: 
	@echo $(DEPENDENCIES) | sed 's/ /\\|/g' > deps.tmp
	@echo $(CLEAN) | sed -r 's/deps.txt|deps.tmp//g' | sed 's/ / \\\n/g' > deps.txt	
	@echo Dependency list saved in deps.txt.
	@echo Copy the list from deps.txt and add it to the Makefile @DEPENDENCIES
	
failingtest :
	@echo
	@echo Running failing tests...
	@echo
	@$(TEST) $(FAILINGTESTFILES)
