# -*- Mode: Makefile -*-
#
# TARGET is specified on the command line
# eg.
# >make -f Makefile.single TARGET=algorithm_for1
#

MODEQ=../modeq
CC=gcc

CFLAGS= -Wall -ansi -pedantic -I../../c_runtime

LDFLAGS= -L../../c_runtime 

MOFILES = $(TARGET:=.mo)
TARGETS = $(MOFILES:.mo=)
OBJS = $(MOFILES:%.mo=%.main.o)
GENC = $(MOFILES:%.mo=%.c)

all : $(MOFILES:.mo=) 


$(TARGETS) : % : %.main.o
	gcc -o $@ $(LDFLAGS) $< -lc_runtime

$(OBJS) : %.main.o : %.c main.c
	@echo compiling $(subst .main.o,,$@)
	@$(CC) $(CFLAGS) \
	-DCFILE_TO_INCLUDE="\"$(subst .main.o,.c,$@)\""\
	 -DCFUNCTION_TO_CALL="$(subst .main.o,,$@)_read_call_write"\
	 -c -o $@ main.c

.SUFFIXES: .mo


.mo.c:
	@$(MODEQ) $< +d=codegen > $(<:.mo=.c)

clean :
	rm -f $(TARGETS)
	rm -f $(OBJS)
	rm -f $(GENC)
	rm -f *~
