# -*- Mode: Makefile -*-
#
# TARGET is specified on the command line
# eg.
# >make -f Makefile.single TARGET=algorithm_for1
#

MODEQ=../modeq
CC=gcc

CFLAGS= -Wall -ansi -pedantic -g -I../../c_runtime

LDFLAGS= -L../../c_runtime -lm

CDIR = csrc
ODIR = obj
BDIR = bin

MOFILES = $(TARGET:=.mo)
TARGETS = $(MOFILES:%.mo=$(BDIR)/%)
OBJS = $(MOFILES:%.mo=$(ODIR)/%.main.o)
GENC = $(MOFILES:%.mo=$(CDIR)/%.c)


all : $(CDIR) $(ODIR) $(BDIR) $(TARGETS) 


$(TARGETS) : $(BDIR)/% : $(ODIR)/%.main.o
	gcc -g -o $@ $(LDFLAGS) $< -lc_runtime

$(OBJS) : $(ODIR)/%.main.o : $(CDIR)/%.c main.c
	@echo compiling $(subst .main.o,,$@)
	$(CC) $(CFLAGS) \
	-DCFILE_TO_INCLUDE="\"$(subst $(ODIR),$(CDIR),$(subst .main.o,.c,$@))\""\
	 -DCFUNCTION_TO_CALL="$(subst $(ODIR)/,,$(subst .main.o,,$@))_read_call_write"\
	 -c -o $@ main.c

$(GENC) : $(CDIR)/%.c : %.mo 
	@$(MODEQ) $< +d=codegen > $@

$(CDIR) $(ODIR) $(BDIR) : % :
	mkdir $@

.SUFFIXES: .mo


.mo.c:
	@$(MODEQ) $< +d=codegen > $(<:.mo=.c)

clean :
	rm -f $(TARGETS)
	rm -f $(OBJS)
	rm -f $(GENC)
	rm -f *~
