.\" --------------------------------------------------------------------
.\" Title 
.\" --------------------------------------------------------------------
.
.TH OMEdit 1 "The Open Source Modelica Consortium" "1.7.0" "The OpenModelica Project" -*- nroff -*-
.
.
.\" -------------------------------------------------------------------- 
.SH NAME
.\" --------------------------------------------------------------------
.
OMEdit \- A Modelica connection editor for OpenModelica
.
.
.\" --------------------------------------------------------------------
.SH "SYNOPSIS"
.\" --------------------------------------------------------------------
.
.B OMEdit
[\fIFILE\fR]...
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
.B OMEdit
is a graphical connection editor for Modelica 3.1 libraries. It uses the
OpenModelica Compiler, \fBomc\fP, for communication.
.
.\" --------------------------------------------------------------------
.SH AUTHOR
.\" --------------------------------------------------------------------
.
See OpenModelicaUsersGuide.pdf for a full list of contributors to the
\%OpenModelica project.
.
.\" --------------------------------------------------------------------
.SH BUGS
.\" --------------------------------------------------------------------
.
If you find a bug, please report it at:
.P
<\fBhttp://openmodelica.org:8080/cb/project/1\fR>
.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
.\" --------------------------------------------------------------------
.
.BR omc (1),
.BR omlibrary-msl31 (1)
.
