#define MODEL_GUID "DUMMY-GUID"

#define NUMBER_OF_REALS 1
#define NUMBER_OF_STATES 1
#define NUMBER_OF_INTEGERS 1
#define NUMBER_OF_BOOLEANS 1
#define NUMBER_OF_STRINGS 1
#define NUMBER_OF_EVENT_INDICATORS 1
#define NUMBER_OF_EXTERNALFUNCTIONS 1

#define STATES { 0 }
#define STATESDERIVATIVES { 1 }
