$header()$
/** Uniontype $uniontype$
  * The classname has been suffixed with _UT because the Windows platform
  * can't handle multiple files with the same case-insensitive filename.
  *
  * MetaModelica uniontypes are traditionally named with only the initial
  * letter capitalized. The member records are named using only capitalized
  * letters.
  */
public interface $uniontype$ extends IModelicaRecord {
}
