name: nightly-release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Create zip
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-nightly.zip ${{ github.event.repository.name }} -r -x '*/.git/*'

      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          files: ${{ github.event.repository.name }}-nightly.zip
