name: on-release

on:
  workflow_dispatch:
  push: # run only on push tags
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Build Assets
        run: |
          cd ..
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-src-with-submodules.zip ${{ github.event.repository.name }} -r -x '*/.git/*'
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*src-with-submodules.zip'
