name: on-release

on:
  workflow_dispatch:
  push: # run only on push tags
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OMVERSION : ''
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: Build Assets
        run: |
          export OMVERSION=`git describe --tags --match "v*.*" --always`
          echo Version: $OMVERSION
          cd ..
          ln -s ${{ github.event.repository.name }} ${{ github.event.repository.name }}-$OMVERSION
          zip ${{ github.event.repository.name }}/${{ github.event.repository.name }}-src-with-submodules.zip ${{ github.event.repository.name }}-$OMVERSION -r -x '*/.git/*'
          rm -f ${{ github.event.repository.name }}-$OMVERSION
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v3
        with:
          files: '*src-with-submodules.zip'
